import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

// GET /api/blog - Get all blog posts
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const published = searchParams.get('published');
    const category = searchParams.get('category');
    const limit = parseInt(searchParams.get('limit') || '20');
    const offset = parseInt(searchParams.get('offset') || '0');
    const search = searchParams.get('search');

    const where: Record<string, unknown> = {};
    
    if (published === 'true') where.published = true;
    if (published === 'false') where.published = false;
    if (category && category !== 'all') where.category = category;
    if (search) {
      where.OR = [
        { title: { contains: search } },
        { excerpt: { contains: search } },
      ];
    }

    const [posts, total] = await Promise.all([
      db.blogPost.findMany({
        where,
        include: { affiliateLinks: { orderBy: { displayOrder: 'asc' } } },
        orderBy: [
          { featured: 'desc' },
          { trending: 'desc' },
          { createdAt: 'desc' },
        ],
        take: limit,
        skip: offset,
      }),
      db.blogPost.count({ where }),
    ]);

    return NextResponse.json({ posts, total, limit, offset });
  } catch (error) {
    console.error('Blog GET error:', error);
    return NextResponse.json({ error: 'Failed to fetch posts' }, { status: 500 });
  }
}

// POST /api/blog - Create a new blog post
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { title, slug, excerpt, content, coverImage, category, tags, seoTitle, seoDesc, featured, trending, published, autoGenerated, sourceUrl, affiliateLinks } = body;

    if (!title || !slug) {
      return NextResponse.json({ error: 'Title and slug are required' }, { status: 400 });
    }

    const post = await db.blogPost.create({
      data: {
        title,
        slug,
        excerpt: excerpt || '',
        content: content || '',
        coverImage,
        category: category || 'AI Tools',
        tags: JSON.stringify(tags || []),
        seoTitle,
        seoDesc,
        featured: featured || false,
        trending: trending || false,
        published: published || false,
        autoGenerated: autoGenerated || false,
        sourceUrl,
        publishedAt: published ? new Date() : null,
      },
    });

    // Create affiliate links if provided
    if (affiliateLinks && Array.isArray(affiliateLinks)) {
      for (let i = 0; i < affiliateLinks.length; i++) {
        const link = affiliateLinks[i];
        await db.affiliateLink.create({
          data: {
            blogPostId: post.id,
            toolName: link.toolName,
            affiliateUrl: link.affiliateUrl,
            commissionRate: link.commissionRate,
            commissionType: link.commissionType || 'recurring',
            description: link.description,
            displayOrder: i,
          },
        });
      }
    }

    const fullPost = await db.blogPost.findUnique({
      where: { id: post.id },
      include: { affiliateLinks: true },
    });

    return NextResponse.json({ post: fullPost }, { status: 201 });
  } catch (error: unknown) {
    console.error('Blog POST error:', error);
    const msg = error instanceof Error && error.message.includes('Unique') ? 'Slug already exists' : 'Failed to create post';
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
