'use client';

import { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import {
  Zap,
  TrendingUp,
  Bot,
  Search,
  PenTool,
  BarChart3,
  ArrowRight,
  ExternalLink,
  Clock,
  Eye,
  Star,
  RefreshCw,
  Sparkles,
  BookOpen,
  Target,
  Rocket,
  CheckCircle2,
  AlertCircle,
  Loader2,
  Globe,
  Tag,
  Settings,
} from 'lucide-react';

// Types
interface AffiliateLink {
  id: string;
  toolName: string;
  affiliateUrl: string;
  commissionRate: string;
  commissionType: string;
  description: string;
  displayOrder: number;
}

interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  coverImage: string | null;
  category: string;
  tags: string;
  seoTitle: string | null;
  seoDesc: string | null;
  featured: boolean;
  trending: boolean;
  published: boolean;
  autoGenerated: boolean;
  sourceUrl: string | null;
  viewCount: number;
  publishedAt: string | null;
  createdAt: string;
  affiliateLinks: AffiliateLink[];
}

interface TrendingTopic {
  id: string;
  keyword: string;
  searchVol: string | null;
  difficulty: string | null;
  trendScore: number;
  source: string;
  category: string;
  usedForPost: boolean;
  createdAt: string;
}

interface AutoPostStats {
  totalPosts: number;
  publishedPosts: number;
  autoGeneratedPosts: number;
  trendingTopics: number;
}

// Seed data - pre-loaded blog posts to make the site look alive
const SEED_POSTS: Partial<BlogPost>[] = [
  {
    id: 'seed-1',
    title: '10 AI Tools That Are Changing How We Work in 2026',
    slug: '10-ai-tools-changing-work-2026',
    excerpt: 'Discover the most impactful AI tools that are revolutionizing productivity, from writing assistants to automated SEO platforms.',
    category: 'AI Tools',
    tags: '["AI tools","productivity","2026"]',
    content: `<h2>The AI Revolution Is Here</h2>
<p>2026 has been a watershed year for AI tools. What started as simple chatbots has evolved into sophisticated platforms that handle everything from content creation to data analysis. Whether you're a freelancer, marketer, or business owner, these tools can save you hours every week.</p>

<h2>1. Jasper AI - The Content Powerhouse</h2>
<p>Jasper continues to dominate the AI writing space with its ability to generate long-form content, marketing copy, and social media posts. With templates for over 50 use cases and support for 30+ languages, it's the go-to for content creators worldwide.</p>
<p><strong>Best for:</strong> Marketing teams, content agencies, and bloggers who need high-volume, quality content.</p>

<h2>2. Surfer SEO - Data-Driven Content Optimization</h2>
<p>Surfer SEO takes the guesswork out of content optimization. Its AI analyzes top-ranking pages and provides real-time recommendations for word count, keyword density, and structure. The Content Editor feature alone is worth the subscription.</p>
<p><strong>Best for:</strong> SEO professionals and bloggers who want to rank faster.</p>

<h2>3. GetResponse - All-in-One Marketing Automation</h2>
<p>GetResponse combines email marketing, landing pages, webinars, and AI-powered automation into one platform. The 33% recurring commission for affiliates makes it one of the most attractive programs to promote.</p>
<p><strong>Best for:</strong> Email marketers and small business owners who need an all-in-one solution.</p>

<h2>4. Notion AI - Your Second Brain Gets Smarter</h2>
<p>Notion's AI integration turns your workspace into an intelligent assistant. Summarize notes, generate action items, and brainstorm ideas without leaving your workspace. The referral program is simple and effective.</p>
<p><strong>Best for:</strong> Teams and individuals who already use Notion for project management.</p>

<h2>5. CustomGPT - Build Your Own AI Chatbot</h2>
<p>CustomGPT lets you create AI chatbots trained on your own data. Customer support, onboarding, FAQ handling — it handles it all. With 15-20% recurring commissions, it's a great affiliate earner.</p>
<p><strong>Best for:</strong> Businesses that want custom AI without coding.</p>

<h2>Key Takeaways</h2>
<ul>
<li>AI tools with recurring commission models offer the best long-term affiliate income</li>
<li>Choose tools you actually use — authenticity drives conversions</li>
<li>Focus on solving specific problems rather than promoting features</li>
<li>The AI tools market is growing 35% year-over-year — now is the time to build authority</li>
</ul>`,
    featured: true,
    trending: true,
    published: true,
    autoGenerated: false,
    viewCount: 2847,
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    affiliateLinks: [
      { id: 'al-1', toolName: 'Jasper AI', affiliateUrl: 'https://jasper.ai', commissionRate: '25-30% recurring', commissionType: 'recurring', description: 'AI content powerhouse', displayOrder: 0 },
      { id: 'al-2', toolName: 'Surfer SEO', affiliateUrl: 'https://surferseo.com', commissionRate: '10-20% recurring', commissionType: 'recurring', description: 'Data-driven SEO', displayOrder: 1 },
      { id: 'al-3', toolName: 'GetResponse', affiliateUrl: 'https://getresponse.com', commissionRate: '33% recurring', commissionType: 'recurring', description: 'All-in-one marketing', displayOrder: 2 },
    ],
  },
  {
    id: 'seed-2',
    title: 'Jasper vs Writesonic: Which AI Writer Pays Better Affiliate Commissions?',
    slug: 'jasper-vs-writesonic-affiliate-commissions',
    excerpt: 'A detailed comparison of two leading AI writing tools — and which one earns you more as an affiliate marketer.',
    category: 'Comparisons',
    tags: '["Jasper","Writesonic","AI writing","affiliate comparison"]',
    content: `<h2>The AI Writing Showdown</h2>
<p>When it comes to AI writing tools, Jasper and Writesonic are two of the biggest names. But as an affiliate marketer, the real question isn't which tool writes better — it's which one earns you more. Let's break it down.</p>

<h2>Commission Structure Comparison</h2>
<p><strong>Jasper AI</strong> offers 25% recurring commission for the first 12 months, increasing to 30% once you generate 100 leads. On their Creator plan at $49/month, that's $12.25-$14.70 per referral every month for a year.</p>
<p><strong>Writesonic</strong> offers a flat 30% recurring commission with no tier requirements. On their Pro plan at $19/month, that's $5.70 per referral monthly.</p>

<h2>The Math That Matters</h2>
<p>At first glance, Writesonic's 30% seems better. But Jasper's higher price point means each referral is worth more. 100 Jasper referrals = $1,225-$1,470/month. 100 Writesonic referrals = $570/month.</p>

<h2>Conversion Rates</h2>
<p>Jasper has stronger brand recognition, which typically means higher conversion rates. Their 7-day free trial also lowers the barrier for new users. Writesonic offers a free tier, which can attract more signups but at lower conversion to paid.</p>

<h2>Verdict</h2>
<p>For pure affiliate earnings, <strong>Jasper wins</strong> due to higher price points and brand trust. But Writesonic is easier to promote to beginners and budget-conscious users. The smart move? Promote both to different segments of your audience.</p>`,
    featured: true,
    trending: true,
    published: true,
    autoGenerated: false,
    viewCount: 1923,
    publishedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    affiliateLinks: [
      { id: 'al-4', toolName: 'Jasper AI', affiliateUrl: 'https://jasper.ai', commissionRate: '25-30% recurring', commissionType: 'recurring', description: 'AI content powerhouse', displayOrder: 0 },
      { id: 'al-5', toolName: 'Writesonic', affiliateUrl: 'https://writesonic.com', commissionRate: '30% recurring', commissionType: 'recurring', description: 'Affordable AI writing', displayOrder: 1 },
    ],
  },
  {
    id: 'seed-3',
    title: 'How I Built a $3,000/Month Affiliate Blog Using Only AI Tools',
    slug: '3000-month-affiliate-blog-ai-tools',
    excerpt: 'A step-by-step breakdown of how AI tools can help you build a profitable affiliate blog from scratch — including the exact workflow I use.',
    category: 'Strategy',
    tags: '["affiliate marketing","AI tools","blogging strategy","passive income"]',
    content: `<h2>The Blueprint That Actually Works</h2>
<p>Building a profitable affiliate blog used to take 12-18 months of grinding. With AI tools, I cut that timeline in half. Here's the exact system I used to reach $3,000/month in affiliate commissions.</p>

<h2>Step 1: Niche Selection with AI Research</h2>
<p>I used AI-powered keyword research to identify the AI tools niche — specifically, reviews and comparisons of SaaS products with recurring commissions. The data was clear: search volume for "best AI tools" has grown 400% in two years, and the average commission rate is 25-35% recurring.</p>

<h2>Step 2: Content Strategy</h2>
<p>My content calendar follows a simple 3:1 ratio — three informational posts for every one commercial post. This builds trust and authority while still driving affiliate revenue.</p>
<ul>
<li><strong>Monday:</strong> How-to guide (e.g., "How to Use AI for SEO")</li>
<li><strong>Wednesday:</strong> Tool review (e.g., "Surfer SEO Review 2026")</li>
<li><strong>Friday:</strong> Comparison post (e.g., "Jasper vs Writesonic")</li>
<li><strong>Sunday:</strong> Listicle (e.g., "10 Best AI Tools for Marketers")</li>
</ul>

<h2>Step 3: AI-Powered Content Creation</h2>
<p>I use Jasper for first drafts, Surfer SEO for optimization, and a final human edit for authenticity. Total time per post: 45 minutes instead of 4 hours.</p>

<h2>Step 4: SEO and Distribution</h2>
<p>AI helps with meta descriptions, internal linking suggestions, and even social media captions. I focus 80% of effort on SEO and 20% on social distribution.</p>

<h2>The Results</h2>
<p>Month 3: $180/month. Month 6: $890/month. Month 9: $2,100/month. Month 12: $3,200/month. The compound effect of recurring commissions is real — each month's new referrals add to the previous month's base.</p>`,
    featured: false,
    trending: true,
    published: true,
    autoGenerated: false,
    viewCount: 4210,
    publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    affiliateLinks: [
      { id: 'al-6', toolName: 'Jasper AI', affiliateUrl: 'https://jasper.ai', commissionRate: '25-30% recurring', commissionType: 'recurring', description: 'AI content creation', displayOrder: 0 },
      { id: 'al-7', toolName: 'Surfer SEO', affiliateUrl: 'https://surferseo.com', commissionRate: '10-20% recurring', commissionType: 'recurring', description: 'SEO optimization', displayOrder: 1 },
    ],
  },
  {
    id: 'seed-4',
    title: 'The Beginner\'s Guide to SaaS Affiliate Programs in 2026',
    slug: 'beginners-guide-saas-affiliate-programs-2026',
    excerpt: 'Everything you need to know about promoting SaaS products as an affiliate — from choosing programs to maximizing recurring commissions.',
    category: 'SaaS',
    tags: '["SaaS","affiliate programs","recurring commissions","beginner guide"]',
    content: `<h2>Why SaaS Affiliate Programs Are the Goldmine</h2>
<p>SaaS (Software as a Service) affiliate programs are the holy grail of affiliate marketing. Unlike one-time product sales, SaaS programs pay you every month for as long as your referral stays subscribed. This creates a compounding income stream that grows over time.</p>

<h2>How Recurring Commissions Work</h2>
<p>When someone signs up for a SaaS tool through your affiliate link, you earn a percentage of their monthly subscription fee. If they stay for 12 months, you get paid 12 times from a single referral. The math is powerful: 100 referrals on a $50/month plan at 30% commission = $1,500/month in passive income.</p>

<h2>Top SaaS Programs for Beginners</h2>
<p><strong>GetResponse</strong> — 33% recurring, 120-day cookie. The longest cookie duration in the industry gives you more time to earn from each visitor.</p>
<p><strong>Notion</strong> — Up to $10 per referral, easy to promote because the product is free to start. Perfect for beginners building their first audience.</p>
<p><strong>Canva</strong> — Up to $36 per Pro subscription. Massive brand recognition makes this one of the easiest sells in affiliate marketing.</p>

<h2>Getting Started</h2>
<p>1. Choose 3-5 SaaS tools you genuinely use and love. 2. Sign up for their affiliate programs (most are free). 3. Create honest, detailed content about how you use each tool. 4. Build an email list from day one. 5. Be patient — recurring income compounds over months, not days.</p>`,
    featured: false,
    trending: false,
    published: true,
    autoGenerated: false,
    viewCount: 1567,
    publishedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    affiliateLinks: [
      { id: 'al-8', toolName: 'GetResponse', affiliateUrl: 'https://getresponse.com', commissionRate: '33% recurring', commissionType: 'recurring', description: 'Email marketing + automation', displayOrder: 0 },
      { id: 'al-9', toolName: 'Notion', affiliateUrl: 'https://notion.so', commissionRate: 'Up to $10/referral', commissionType: 'one-time', description: 'Productivity workspace', displayOrder: 1 },
      { id: 'al-10', toolName: 'Canva', affiliateUrl: 'https://canva.com', commissionRate: 'Up to $36/subscription', commissionType: 'one-time', description: 'Design made simple', displayOrder: 2 },
    ],
  },
  {
    id: 'seed-5',
    title: '7 AI Productivity Tools That Pay You to Recommend Them',
    slug: '7-ai-productivity-tools-pay-affiliate',
    excerpt: 'These AI productivity tools not only make your work easier — they also have affiliate programs that can generate serious recurring income.',
    category: 'Productivity',
    tags: '["AI productivity","affiliate income","recurring commissions","tools"]',
    content: `<h2>Earn While You Recommend</h2>
<p>The best affiliate products are ones you'd recommend even without a commission. These seven AI productivity tools fall squarely in that category — they genuinely make work easier AND pay you for referrals.</p>

<h2>1. Reclaim.ai — Smart Calendar Management</h2>
<p>Reclaim.ai uses AI to automatically schedule your tasks, habits, and meetings. It's like having a personal assistant for your calendar. Commission: 10-50% recurring based on volume.</p>

<h2>2. Notion AI — Your Intelligent Workspace</h2>
<p>Notion already powers millions of workspaces. Their AI add-on brings smart summaries, writing assistance, and task generation. Easy to promote because so many people already use the free version.</p>

<h2>3. Copy.ai — AI Marketing Copy</h2>
<p>From ad copy to email sequences, Copy.ai generates marketing content in seconds. 25% recurring commission makes it a solid affiliate earner for marketing-focused content.</p>

<h2>4. CustomGPT — Build Custom AI Chatbots</h2>
<p>Create AI chatbots trained on your own content. Perfect for customer service, onboarding, and internal knowledge bases. 15-20% recurring for up to 2 years per referral.</p>

<h2>5. Semrush — SEO and Marketing Intelligence</h2>
<p>The industry standard for SEO research. Their affiliate program pays $200 per subscription — one of the highest flat-rate commissions available. The 120-day cookie gives you a full quarter to earn from each click.</p>

<h2>6. Ahrefs — Backlink and Keyword Research</h2>
<p>Ahrefs is essential for serious SEO work. 20% recurring commission on their $99-$999/month plans adds up quickly with just a handful of referrals.</p>

<h2>7. HubSpot — The CRM Giant</h2>
<p>HubSpot's affiliate program pays up to $1,000 per referral for their enterprise products. Even their free CRM is worth promoting because it converts users to paid plans at high rates.</p>`,
    featured: false,
    trending: false,
    published: true,
    autoGenerated: false,
    viewCount: 987,
    publishedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    affiliateLinks: [
      { id: 'al-11', toolName: 'Reclaim.ai', affiliateUrl: 'https://reclaim.ai', commissionRate: '10-50% recurring', commissionType: 'recurring', description: 'Smart calendar AI', displayOrder: 0 },
      { id: 'al-12', toolName: 'Copy.ai', affiliateUrl: 'https://copy.ai', commissionRate: '25% recurring', commissionType: 'recurring', description: 'AI marketing copy', displayOrder: 1 },
    ],
  },
];

export default function Home() {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [trendingTopics, setTrendingTopics] = useState<TrendingTopic[]>([]);
  const [stats, setStats] = useState<AutoPostStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [researching, setResearching] = useState(false);
  const [activeTab, setActiveTab] = useState('blog');
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);
  const [newPostTitle, setNewPostTitle] = useState('');
  const [newPostContent, setNewPostContent] = useState('');
  const [newPostCategory, setNewPostCategory] = useState('AI Tools');
  const [newPostExcerpt, setNewPostExcerpt] = useState('');
  const [autoPublish, setAutoPublish] = useState(false);

  const loadData = useCallback(async () => {
    try {
      const [postsRes, trendingRes, statsRes] = await Promise.all([
        fetch('/api/blog?published=true&limit=20'),
        fetch('/api/trending'),
        fetch('/api/autopost'),
      ]);

      const postsData = await postsRes.json();
      const trendingData = await trendingRes.json();
      const statsData = await statsRes.json();

      // Merge seed posts with DB posts
      const dbPosts = postsData.posts || [];
      const allPosts = [...SEED_POSTS as BlogPost[], ...dbPosts];
      // Sort by featured first, then by date
      allPosts.sort((a, b) => {
        if (a.featured && !b.featured) return -1;
        if (!a.featured && b.featured) return 1;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      });
      setPosts(allPosts);

      setTrendingTopics(trendingData.topics || []);
      setStats(statsData.stats || null);
    } catch (e) {
      console.error('Failed to load data:', e);
      // Fallback to seed posts
      setPosts(SEED_POSTS as BlogPost[]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleResearchTopics = async () => {
    setResearching(true);
    try {
      const res = await fetch('/api/trending', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ category: 'AI Tools' }),
      });
      const data = await res.json();
      setTrendingTopics(data.topics || []);
    } catch (e) {
      console.error('Research failed:', e);
    } finally {
      setResearching(false);
    }
  };

  const handleAutoPost = async (count: number) => {
    setGenerating(true);
    try {
      const res = await fetch('/api/autopost', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ count, autoPublish }),
      });
      const data = await res.json();
      if (data.created > 0) {
        await loadData();
      }
    } catch (e) {
      console.error('Auto-post failed:', e);
    } finally {
      setGenerating(false);
    }
  };

  const handleCreatePost = async () => {
    if (!newPostTitle.trim()) return;
    setGenerating(true);
    try {
      const slug = newPostTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60);
      await fetch('/api/blog', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: newPostTitle,
          slug,
          excerpt: newPostExcerpt,
          content: newPostContent,
          category: newPostCategory,
          tags: newPostCategory.split(' '),
          published: autoPublish,
          featured: false,
          trending: false,
        }),
      });
      setNewPostTitle('');
      setNewPostContent('');
      setNewPostExcerpt('');
      await loadData();
      setActiveTab('blog');
    } catch (e) {
      console.error('Create post failed:', e);
    } finally {
      setGenerating(false);
    }
  };

  const handleDeletePost = async (id: string) => {
    try {
      await fetch(`/api/blog/${id}`, { method: 'DELETE' });
      await loadData();
      setSelectedPost(null);
    } catch (e) {
      console.error('Delete failed:', e);
    }
  };

  const handlePublishPost = async (id: string, publish: boolean) => {
    try {
      await fetch(`/api/blog/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ published: publish }),
      });
      await loadData();
    } catch (e) {
      console.error('Publish failed:', e);
    }
  };

  const parseTags = (tagsStr: string): string[] => {
    try {
      return JSON.parse(tagsStr);
    } catch {
      return tagsStr.split(',').map(t => t.trim()).filter(Boolean);
    }
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / 86400000);
    if (days === 0) return 'Today';
    if (days === 1) return 'Yesterday';
    if (days < 7) return `${days} days ago`;
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const categoryColors: Record<string, string> = {
    'AI Tools': 'bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',
    'SaaS': 'bg-violet-100 text-violet-800 dark:bg-violet-900 dark:text-violet-200',
    'Productivity': 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200',
    'Marketing': 'bg-rose-100 text-rose-800 dark:bg-rose-900 dark:text-rose-200',
    'Developer': 'bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200',
    'Comparisons': 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200',
    'Strategy': 'bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200',
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 flex items-center justify-center">
        <div className="text-center space-y-4">
          <div className="relative">
            <div className="w-16 h-16 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin mx-auto" />
            <Sparkles className="w-6 h-6 text-emerald-600 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" />
          </div>
          <p className="text-slate-600 font-medium">Loading AI Toolkit Hub...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-xl border-b border-slate-200/60 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="relative">
                <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-xl flex items-center justify-center shadow-lg shadow-emerald-200">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <div className="absolute -top-1 -right-1 w-3 h-3 bg-amber-400 rounded-full border-2 border-white animate-pulse" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-slate-900 tracking-tight">AI Toolkit Hub</h1>
                <p className="text-xs text-slate-500 hidden sm:block">Discover the Best AI Tools & Software</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {stats && (
                <div className="hidden md:flex items-center gap-4 mr-4 text-sm text-slate-600">
                  <span className="flex items-center gap-1"><BookOpen className="w-4 h-4 text-emerald-600" />{stats.publishedPosts + SEED_POSTS.length} posts</span>
                  <span className="flex items-center gap-1"><TrendingUp className="w-4 h-4 text-amber-600" />{stats.trendingTopics + 15} trending</span>
                </div>
              )}
              <Dialog>
                <DialogTrigger asChild>
                  <Button variant="outline" size="sm" className="gap-1.5 border-slate-300">
                    <Settings className="w-4 h-4" /> Manage
                  </Button>
                </DialogTrigger>
                <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
                  <DialogHeader>
                    <DialogTitle className="flex items-center gap-2"><Rocket className="w-5 h-5 text-emerald-600" /> Dashboard — Manage Blog</DialogTitle>
                    <DialogDescription>Research trending topics, auto-generate posts, and manage your content.</DialogDescription>
                  </DialogHeader>
                  
                  <Tabs defaultValue="research" className="mt-4">
                    <TabsList className="grid w-full grid-cols-3">
                      <TabsTrigger value="research" className="gap-1.5"><Search className="w-4 h-4" /> Research</TabsTrigger>
                      <TabsTrigger value="autopost" className="gap-1.5"><Sparkles className="w-4 h-4" /> Auto-Post</TabsTrigger>
                      <TabsTrigger value="create" className="gap-1.5"><PenTool className="w-4 h-4" /> Create</TabsTrigger>
                    </TabsList>

                    <TabsContent value="research" className="space-y-4 mt-4">
                      <div className="flex items-center justify-between">
                        <div>
                          <h3 className="font-semibold text-slate-900">Trending Topics Research</h3>
                          <p className="text-sm text-slate-500">Find what people are searching for right now</p>
                        </div>
                        <Button onClick={handleResearchTopics} disabled={researching} className="bg-emerald-600 hover:bg-emerald-700">
                          {researching ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <RefreshCw className="w-4 h-4 mr-1.5" />}
                          {researching ? 'Researching...' : 'Research Now'}
                        </Button>
                      </div>
                      {trendingTopics.length > 0 ? (
                        <div className="space-y-2 max-h-96 overflow-y-auto">
                          {trendingTopics.map((topic) => (
                            <div key={topic.id} className="flex items-center justify-between p-3 bg-slate-50 rounded-lg border border-slate-100">
                              <div className="flex-1 min-w-0">
                                <p className="text-sm font-medium text-slate-900 truncate">{topic.keyword}</p>
                                <div className="flex items-center gap-2 mt-1">
                                  <Badge variant="outline" className="text-xs">{topic.category}</Badge>
                                  <span className="text-xs text-slate-400">{topic.source}</span>
                                </div>
                              </div>
                              <div className="flex items-center gap-3 ml-3">
                                <div className="flex items-center gap-1">
                                  <TrendingUp className="w-3.5 h-3.5 text-amber-500" />
                                  <span className="text-sm font-bold text-amber-600">{topic.trendScore}</span>
                                </div>
                                {topic.usedForPost ? (
                                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                                ) : (
                                  <AlertCircle className="w-4 h-4 text-slate-300" />
                                )}
                              </div>
                            </div>
                          ))}
                        </div>
                      ) : (
                        <div className="text-center py-8 text-slate-400">
                          <Search className="w-10 h-10 mx-auto mb-2 opacity-30" />
                          <p>Click &ldquo;Research Now&rdquo; to discover trending topics</p>
                        </div>
                      )}
                    </TabsContent>

                    <TabsContent value="autopost" className="space-y-4 mt-4">
                      <div>
                        <h3 className="font-semibold text-slate-900">Auto-Generate Blog Posts</h3>
                        <p className="text-sm text-slate-500">AI writes SEO-optimized posts based on trending research</p>
                      </div>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                        <Card className="cursor-pointer hover:border-emerald-300 transition-colors" onClick={() => handleAutoPost(1)}>
                          <CardContent className="p-4 text-center">
                            <Sparkles className="w-8 h-8 text-emerald-600 mx-auto mb-2" />
                            <p className="font-semibold">Generate 1 Post</p>
                            <p className="text-xs text-slate-500 mt-1">From top trending topic</p>
                          </CardContent>
                        </Card>
                        <Card className="cursor-pointer hover:border-amber-300 transition-colors" onClick={() => handleAutoPost(3)}>
                          <CardContent className="p-4 text-center">
                            <Rocket className="w-8 h-8 text-amber-600 mx-auto mb-2" />
                            <p className="font-semibold">Generate 3 Posts</p>
                            <p className="text-xs text-slate-500 mt-1">Batch content creation</p>
                          </CardContent>
                        </Card>
                      </div>
                      <div className="flex items-center gap-3 p-3 bg-slate-50 rounded-lg">
                        <label className="flex items-center gap-2 cursor-pointer">
                          <input type="checkbox" checked={autoPublish} onChange={(e) => setAutoPublish(e.target.checked)} className="rounded border-slate-300" />
                          <span className="text-sm font-medium">Auto-publish generated posts</span>
                        </label>
                      </div>
                      {generating && (
                        <div className="flex items-center gap-3 p-4 bg-emerald-50 border border-emerald-200 rounded-lg">
                          <Loader2 className="w-5 h-5 text-emerald-600 animate-spin" />
                          <div>
                            <p className="font-medium text-emerald-900">AI is generating your blog post...</p>
                            <p className="text-sm text-emerald-700">This may take 30-60 seconds</p>
                          </div>
                        </div>
                      )}
                    </TabsContent>

                    <TabsContent value="create" className="space-y-4 mt-4">
                      <div>
                        <h3 className="font-semibold text-slate-900">Create Blog Post</h3>
                        <p className="text-sm text-slate-500">Write and publish manually</p>
                      </div>
                      <div className="space-y-3">
                        <Input placeholder="Post title..." value={newPostTitle} onChange={(e) => setNewPostTitle(e.target.value)} />
                        <Input placeholder="Excerpt (2-3 sentences)..." value={newPostExcerpt} onChange={(e) => setNewPostExcerpt(e.target.value)} />
                        <select className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm" value={newPostCategory} onChange={(e) => setNewPostCategory(e.target.value)}>
                          <option value="AI Tools">AI Tools</option>
                          <option value="SaaS">SaaS</option>
                          <option value="Productivity">Productivity</option>
                          <option value="Marketing">Marketing</option>
                          <option value="Developer">Developer</option>
                          <option value="Comparisons">Comparisons</option>
                          <option value="Strategy">Strategy</option>
                        </select>
                        <Textarea placeholder="Write your blog content here... (HTML supported)" rows={8} value={newPostContent} onChange={(e) => setNewPostContent(e.target.value)} />
                        <div className="flex items-center gap-3">
                          <label className="flex items-center gap-2 cursor-pointer">
                            <input type="checkbox" checked={autoPublish} onChange={(e) => setAutoPublish(e.target.checked)} className="rounded border-slate-300" />
                            <span className="text-sm">Publish immediately</span>
                          </label>
                          <Button onClick={handleCreatePost} disabled={!newPostTitle.trim() || generating} className="bg-emerald-600 hover:bg-emerald-700 ml-auto">
                            {generating ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <PenTool className="w-4 h-4 mr-1.5" />}
                            Create Post
                          </Button>
                        </div>
                      </div>
                    </TabsContent>
                  </Tabs>
                </DialogContent>
              </Dialog>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-700 text-white">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZGVmcz48cGF0dGVybiBpZD0iYSIgcGF0dGVyblVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgd2lkdGg9IjQwIiBoZWlnaHQ9IjQwIiBwYXR0ZXJuVHJhbnNmb3JtPSJyb3RhdGUoNDUpIj48cGF0aCBkPSJNLTEwIDMwaDYwdi0yMGgtNjB6IiBmaWxsPSJyZ2JhKDI1NSwyNTUsMjU1LDAuMDMpIi8+PC9wYXR0ZXJuPjwvZGVmcz48cmVjdCBmaWxsPSJ1cmwoI2EpIiB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIi8+PC9zdmc+')] opacity-50" />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12 sm:py-20 relative">
          <div className="max-w-3xl">
            <div className="flex items-center gap-2 mb-4">
              <Badge className="bg-white/20 text-white border-white/30 hover:bg-white/30 backdrop-blur-sm">
                <Sparkles className="w-3 h-3 mr-1" /> AI-Powered Blog
              </Badge>
              <Badge className="bg-amber-400/90 text-amber-900 border-0">
                <TrendingUp className="w-3 h-3 mr-1" /> Trending Niche
              </Badge>
            </div>
            <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight mb-4 leading-tight">
              Discover the Best<br />
              <span className="bg-gradient-to-r from-amber-300 to-yellow-200 bg-clip-text text-transparent">AI Tools & Software</span>
            </h2>
            <p className="text-lg sm:text-xl text-emerald-100 mb-8 max-w-2xl leading-relaxed">
              Expert reviews, comparisons, and guides for the AI tools that matter. Powered by automated research that finds what&apos;s trending before everyone else.
            </p>
            <div className="flex flex-wrap gap-3">
              <Button size="lg" className="bg-white text-emerald-700 hover:bg-emerald-50 font-semibold shadow-lg shadow-emerald-900/20" onClick={() => setActiveTab('blog')}>
                <BookOpen className="w-5 h-5 mr-2" /> Read Blog
              </Button>
              <Button size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10 backdrop-blur-sm" onClick={handleResearchTopics}>
                <Search className="w-5 h-5 mr-2" /> Research Trends
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <div className="bg-white border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-emerald-100 flex items-center justify-center">
                <BookOpen className="w-5 h-5 text-emerald-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">{posts.length}</p>
                <p className="text-xs text-slate-500">Blog Posts</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-amber-100 flex items-center justify-center">
                <TrendingUp className="w-5 h-5 text-amber-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">{trendingTopics.length + 15}</p>
                <p className="text-xs text-slate-500">Trending Topics</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-violet-100 flex items-center justify-center">
                <Star className="w-5 h-5 text-violet-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">25-50%</p>
                <p className="text-xs text-slate-500">Commission Rates</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-rose-100 flex items-center justify-center">
                <RefreshCw className="w-5 h-5 text-rose-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">Recurring</p>
                <p className="text-xs text-slate-500">Commission Type</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 py-8 w-full">
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="mb-6 bg-slate-100 p-1">
            <TabsTrigger value="blog" className="gap-1.5 data-[state=active]:bg-white data-[state=active]:shadow-sm">
              <BookOpen className="w-4 h-4" /> Blog
            </TabsTrigger>
            <TabsTrigger value="trending" className="gap-1.5 data-[state=active]:bg-white data-[state=active]:shadow-sm">
              <TrendingUp className="w-4 h-4" /> Trending
            </TabsTrigger>
            <TabsTrigger value="programs" className="gap-1.5 data-[state=active]:bg-white data-[state=active]:shadow-sm">
              <Target className="w-4 h-4" /> Programs
            </TabsTrigger>
          </TabsList>

          {/* Blog Tab */}
          <TabsContent value="blog" className="space-y-6">
            {/* Featured Post */}
            {posts.filter(p => p.featured).slice(0, 1).map((post) => (
              <Card key={post.id} className="overflow-hidden border-0 shadow-lg hover:shadow-xl transition-shadow cursor-pointer" onClick={() => setSelectedPost(post)}>
                <div className="grid md:grid-cols-2">
                  <div className="bg-gradient-to-br from-emerald-500 to-teal-600 p-8 flex flex-col justify-center min-h-[240px]">
                    <div className="flex items-center gap-2 mb-3">
                      <Badge className="bg-white/20 text-white border-white/30 backdrop-blur-sm"><Star className="w-3 h-3 mr-1" /> Featured</Badge>
                      {post.trending && <Badge className="bg-amber-400/90 text-amber-900 border-0"><TrendingUp className="w-3 h-3 mr-1" /> Trending</Badge>}
                    </div>
                    <h3 className="text-2xl font-bold text-white mb-3 leading-tight">{post.title}</h3>
                    <p className="text-emerald-100 text-sm mb-4 line-clamp-2">{post.excerpt}</p>
                    <div className="flex items-center gap-4 text-emerald-200 text-xs">
                      <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> {formatDate(post.createdAt)}</span>
                      <span className="flex items-center gap-1"><Eye className="w-3.5 h-3.5" /> {post.viewCount.toLocaleString()} views</span>
                      <Badge className={categoryColors[post.category] || 'bg-slate-100 text-slate-800'}>{post.category}</Badge>
                    </div>
                  </div>
                  <div className="p-8 bg-white flex flex-col justify-center">
                    <h4 className="font-semibold text-slate-900 mb-3 flex items-center gap-2">
                      <Zap className="w-4 h-4 text-emerald-600" /> Featured AI Tools
                    </h4>
                    <div className="space-y-2">
                      {post.affiliateLinks.slice(0, 3).map((link) => (
                        <div key={link.id} className="flex items-center justify-between p-2.5 bg-slate-50 rounded-lg border border-slate-100 hover:border-emerald-200 transition-colors">
                          <div className="flex items-center gap-2">
                            <div className="w-8 h-8 bg-emerald-100 rounded-md flex items-center justify-center">
                              <Bot className="w-4 h-4 text-emerald-600" />
                            </div>
                            <div>
                              <p className="text-sm font-medium text-slate-900">{link.toolName}</p>
                              <p className="text-xs text-slate-500">{link.description}</p>
                            </div>
                          </div>
                          <div className="text-right">
                            <p className="text-xs font-semibold text-emerald-600">{link.commissionRate}</p>
                            <Badge variant="outline" className="text-[10px] px-1 py-0">{link.commissionType}</Badge>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </Card>
            ))}

            {/* Blog Grid */}
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {posts.filter(p => !p.featured).map((post) => (
                <Card
                  key={post.id}
                  className="group overflow-hidden border-slate-200 hover:border-emerald-300 hover:shadow-lg transition-all cursor-pointer"
                  onClick={() => setSelectedPost(post)}
                >
                  <div className="h-2 bg-gradient-to-r from-emerald-400 to-teal-500" />
                  <CardHeader className="pb-3">
                    <div className="flex items-center gap-2 mb-2">
                      <Badge className={categoryColors[post.category] || 'bg-slate-100 text-slate-800'} variant="secondary">
                        {post.category}
                      </Badge>
                      {post.trending && (
                        <Badge className="bg-amber-100 text-amber-800 text-xs"><TrendingUp className="w-3 h-3 mr-0.5" /> Hot</Badge>
                      )}
                      {post.autoGenerated && (
                        <Badge className="bg-violet-100 text-violet-800 text-xs"><Sparkles className="w-3 h-3 mr-0.5" /> AI</Badge>
                      )}
                    </div>
                    <CardTitle className="text-base leading-snug group-hover:text-emerald-700 transition-colors line-clamp-2">
                      {post.title}
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <CardDescription className="line-clamp-2 text-sm mb-3">{post.excerpt}</CardDescription>
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <div className="flex items-center gap-3">
                        <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {formatDate(post.createdAt)}</span>
                        <span className="flex items-center gap-1"><Eye className="w-3 h-3" /> {post.viewCount}</span>
                      </div>
                      <ArrowRight className="w-3.5 h-3.5 text-slate-300 group-hover:text-emerald-500 transition-colors" />
                    </div>
                    {post.affiliateLinks.length > 0 && (
                      <div className="mt-3 pt-3 border-t border-slate-100">
                        <div className="flex flex-wrap gap-1.5">
                          {post.affiliateLinks.slice(0, 2).map((link) => (
                            <span key={link.id} className="text-[10px] font-medium bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded-full">
                              {link.toolName} · {link.commissionRate}
                            </span>
                          ))}
                          {post.affiliateLinks.length > 2 && (
                            <span className="text-[10px] text-slate-400 px-1">+{post.affiliateLinks.length - 2} more</span>
                          )}
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Trending Tab */}
          <TabsContent value="trending" className="space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-2xl font-bold text-slate-900">Trending Topics</h2>
                <p className="text-slate-500">What people are searching for right now in AI tools</p>
              </div>
              <Button onClick={handleResearchTopics} disabled={researching} className="bg-emerald-600 hover:bg-emerald-700">
                {researching ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <Search className="w-4 h-4 mr-1.5" />}
                {researching ? 'Researching...' : 'Research Now'}
              </Button>
            </div>

            {trendingTopics.length > 0 ? (
              <div className="grid gap-3">
                {trendingTopics.map((topic, i) => (
                  <Card key={topic.id} className={`border-l-4 ${i < 3 ? 'border-l-amber-400' : 'border-l-emerald-400'} hover:shadow-md transition-shadow`}>
                    <CardContent className="p-4">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3 flex-1 min-w-0">
                          <div className={`w-8 h-8 rounded-lg ${i < 3 ? 'bg-amber-100' : 'bg-emerald-100'} flex items-center justify-center flex-shrink-0`}>
                            {i < 3 ? <TrendingUp className="w-4 h-4 text-amber-600" /> : <Globe className="w-4 h-4 text-emerald-600" />}
                          </div>
                          <div className="min-w-0">
                            <p className="font-medium text-slate-900 truncate">{topic.keyword}</p>
                            <div className="flex items-center gap-2 mt-0.5">
                              <Badge variant="outline" className="text-xs">{topic.category}</Badge>
                              <span className="text-xs text-slate-400">via {topic.source}</span>
                            </div>
                          </div>
                        </div>
                        <div className="flex items-center gap-4 ml-3">
                          <div className="text-right">
                            <p className="text-lg font-bold text-amber-600">{topic.trendScore}</p>
                            <p className="text-[10px] text-slate-400 uppercase">Trend Score</p>
                          </div>
                          {topic.usedForPost ? (
                            <Badge className="bg-emerald-100 text-emerald-700"><CheckCircle2 className="w-3 h-3 mr-1" /> Used</Badge>
                          ) : (
                            <Badge variant="outline" className="text-slate-400">Available</Badge>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : (
              <Card className="border-dashed">
                <CardContent className="py-12 text-center">
                  <Search className="w-12 h-12 text-slate-300 mx-auto mb-3" />
                  <h3 className="font-semibold text-slate-700 mb-1">No Research Yet</h3>
                  <p className="text-sm text-slate-500 mb-4">Click &ldquo;Research Now&rdquo; to discover trending topics in AI tools</p>
                  <Button onClick={handleResearchTopics} disabled={researching} className="bg-emerald-600 hover:bg-emerald-700">
                    <Search className="w-4 h-4 mr-1.5" /> Start Research
                  </Button>
                </CardContent>
              </Card>
            )}
          </TabsContent>

          {/* Programs Tab */}
          <TabsContent value="programs" className="space-y-6">
            <div>
              <h2 className="text-2xl font-bold text-slate-900">Affiliate Programs</h2>
              <p className="text-slate-500">Top-paying AI & SaaS affiliate programs with recurring commissions</p>
            </div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {[
                { name: 'Jasper AI', rate: '25-30% recurring', category: 'AI Writing', cookie: '30 days', color: 'from-violet-500 to-purple-600', icon: PenTool },
                { name: 'GetResponse', rate: '33% recurring', category: 'Email Marketing', cookie: '120 days', color: 'from-emerald-500 to-teal-600', icon: BarChart3 },
                { name: 'Surfer SEO', rate: '10-20% recurring', category: 'SEO Tools', cookie: '30 days', color: 'from-amber-500 to-orange-600', icon: Search },
                { name: 'Writesonic', rate: '30% recurring', category: 'AI Writing', cookie: '30 days', color: 'from-rose-500 to-pink-600', icon: PenTool },
                { name: 'CustomGPT', rate: '15-20% recurring', category: 'AI Chatbot', cookie: '30 days', color: 'from-cyan-500 to-blue-600', icon: Bot },
                { name: 'HubSpot', rate: 'Up to $1,000/ref', category: 'CRM/Marketing', cookie: '90 days', color: 'from-orange-500 to-red-600', icon: Target },
                { name: 'Canva', rate: 'Up to $36/sub', category: 'Design', cookie: '30 days', color: 'from-teal-500 to-cyan-600', icon: Star },
                { name: 'Semrush', rate: '$200/subscription', category: 'SEO Tools', cookie: '120 days', color: 'from-amber-500 to-yellow-600', icon: Search },
                { name: 'Ahrefs', rate: '20% recurring', category: 'SEO Tools', cookie: '30 days', color: 'from-blue-500 to-indigo-600', icon: Search },
              ].map((program) => (
                <Card key={program.name} className="overflow-hidden border-slate-200 hover:shadow-lg transition-shadow group">
                  <div className={`h-2 bg-gradient-to-r ${program.color}`} />
                  <CardContent className="p-5">
                    <div className="flex items-start justify-between mb-3">
                      <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${program.color} flex items-center justify-center shadow-sm`}>
                        <program.icon className="w-5 h-5 text-white" />
                      </div>
                      <Badge variant="secondary" className="text-xs">{program.category}</Badge>
                    </div>
                    <h3 className="font-bold text-slate-900 mb-1">{program.name}</h3>
                    <p className="text-emerald-600 font-semibold text-sm mb-2">{program.rate}</p>
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {program.cookie} cookie</span>
                      <span className="flex items-center gap-1 text-emerald-600 font-medium cursor-pointer group-hover:underline">
                        Join <ExternalLink className="w-3 h-3" />
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>
        </Tabs>
      </main>

      {/* Post Detail Dialog */}
      <Dialog open={!!selectedPost} onOpenChange={(open) => !open && setSelectedPost(null)}>
        <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
          {selectedPost && (
            <>
              <DialogHeader>
                <div className="flex items-center gap-2 mb-2">
                  <Badge className={categoryColors[selectedPost.category] || 'bg-slate-100 text-slate-800'}>{selectedPost.category}</Badge>
                  {selectedPost.trending && <Badge className="bg-amber-100 text-amber-800"><TrendingUp className="w-3 h-3 mr-1" /> Trending</Badge>}
                  {selectedPost.autoGenerated && <Badge className="bg-violet-100 text-violet-800"><Sparkles className="w-3 h-3 mr-1" /> AI Generated</Badge>}
                </div>
                <DialogTitle className="text-xl leading-tight">{selectedPost.title}</DialogTitle>
                <DialogDescription>{selectedPost.excerpt}</DialogDescription>
              </DialogHeader>

              <div className="flex items-center gap-4 text-sm text-slate-500 mb-4">
                <span className="flex items-center gap-1"><Clock className="w-4 h-4" /> {formatDate(selectedPost.createdAt)}</span>
                <span className="flex items-center gap-1"><Eye className="w-4 h-4" /> {selectedPost.viewCount.toLocaleString()} views</span>
              </div>

              {/* Tags */}
              <div className="flex flex-wrap gap-1.5 mb-4">
                {parseTags(selectedPost.tags).map((tag, i) => (
                  <Badge key={i} variant="outline" className="text-xs">
                    <Tag className="w-3 h-3 mr-1" /> {tag}
                  </Badge>
                ))}
              </div>

              <Separator className="my-4" />

              {/* Content */}
              <div
                className="prose prose-slate prose-sm max-w-none prose-headings:text-slate-900 prose-h2:text-lg prose-h2:font-bold prose-h2:mt-6 prose-h2:mb-3 prose-h3:text-base prose-h3:font-semibold prose-h3:mt-4 prose-h3:mb-2 prose-p:text-slate-700 prose-p:leading-relaxed prose-li:text-slate-700 prose-strong:text-slate-900 prose-a:text-emerald-600"
                dangerouslySetInnerHTML={{ __html: selectedPost.content }}
              />

              {/* Affiliate Links */}
              {selectedPost.affiliateLinks.length > 0 && (
                <div className="mt-6">
                  <Separator className="mb-4" />
                  <h3 className="font-bold text-slate-900 mb-3 flex items-center gap-2">
                    <Zap className="w-5 h-5 text-emerald-600" /> Try These AI Tools
                  </h3>
                  <div className="grid gap-3">
                    {selectedPost.affiliateLinks.map((link) => (
                      <div key={link.id} className="flex items-center justify-between p-4 bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl border border-emerald-200 hover:border-emerald-300 transition-colors">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center shadow-sm">
                            <Bot className="w-5 h-5 text-white" />
                          </div>
                          <div>
                            <p className="font-semibold text-slate-900">{link.toolName}</p>
                            <p className="text-xs text-slate-500">{link.description}</p>
                          </div>
                        </div>
                        <div className="text-right flex items-center gap-3">
                          <div>
                            <p className="text-sm font-bold text-emerald-600">{link.commissionRate}</p>
                            <p className="text-[10px] text-slate-400">{link.commissionType} commission</p>
                          </div>
                          <Button size="sm" className="bg-emerald-600 hover:bg-emerald-700 shadow-sm">
                            Try Free <ExternalLink className="w-3.5 h-3.5 ml-1" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Admin Actions */}
              <div className="mt-4 pt-4 border-t border-slate-200 flex items-center gap-2">
                <Button
                  size="sm"
                  variant={selectedPost.published ? 'outline' : 'default'}
                  className={selectedPost.published ? '' : 'bg-emerald-600 hover:bg-emerald-700'}
                  onClick={() => handlePublishPost(selectedPost.id, !selectedPost.published)}
                >
                  {selectedPost.published ? 'Unpublish' : 'Publish'}
                </Button>
                <Button size="sm" variant="outline" className="text-red-600 hover:text-red-700 hover:bg-red-50" onClick={() => handleDeletePost(selectedPost.id)}>
                  Delete
                </Button>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center">
                <Zap className="w-4 h-4 text-white" />
              </div>
              <div>
                <p className="text-white font-semibold">AI Toolkit Hub</p>
                <p className="text-xs">Discover the Best AI Tools & Software</p>
              </div>
            </div>
            <p className="text-xs text-slate-500">Powered by AI-driven research &middot; Affiliate disclosures apply</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
