'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { Separator } from '@/components/ui/separator';
import {
  Zap, TrendingUp, Bot, Search, PenTool, BarChart3, ArrowRight,
  ExternalLink, Clock, Eye, Star, RefreshCw, Sparkles, BookOpen,
  Target, Rocket, CheckCircle2, AlertCircle, Loader2, Globe, Tag,
  Settings, Heart, Share2, MessageCircle, Send, Mail, User,
  ChevronUp, ThumbsUp, Bookmark, Copy, Check, Quote,
} from 'lucide-react';

// Types
interface AffiliateLink {
  id: string;
  toolName: string;
  affiliateUrl: string;
  commissionRate: string;
  commissionType: string;
  description: string;
  displayOrder: number;
}

interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  coverImage: string | null;
  category: string;
  tags: string;
  seoTitle: string | null;
  seoDesc: string | null;
  featured: boolean;
  trending: boolean;
  published: boolean;
  autoGenerated: boolean;
  sourceUrl: string | null;
  viewCount: number;
  likeCount: number;
  shareCount: number;
  commentCount: number;
  authorName: string;
  readTime: number;
  publishedAt: string | null;
  createdAt: string;
  affiliateLinks: AffiliateLink[];
}

interface Comment {
  id: string;
  blogPostId: string;
  authorName: string;
  content: string;
  parentId: string | null;
  liked: number;
  createdAt: string;
}

interface TrendingTopic {
  id: string;
  keyword: string;
  searchVol: string | null;
  difficulty: string | null;
  trendScore: number;
  source: string;
  category: string;
  usedForPost: boolean;
  createdAt: string;
}

interface AutoPostStats {
  totalPosts: number;
  publishedPosts: number;
  autoGeneratedPosts: number;
  trendingTopics: number;
}

// Seed data - pre-loaded blog posts
const SEED_POSTS: Partial<BlogPost>[] = [
  {
    id: 'seed-1', title: '10 AI Tools That Are Changing How We Work in 2026', slug: '10-ai-tools-changing-work-2026',
    excerpt: 'Discover the most impactful AI tools revolutionizing productivity — from writing assistants to automated SEO platforms that save 20+ hours per week.',
    category: 'AI Tools', tags: '["AI tools","productivity","2026","automation","SaaS"]',
    content: `<h2>The AI Revolution Is Already Here</h2>
<p><em>"The businesses that adopt AI tools in 2026 won't just survive — they'll make their competitors irrelevant."</em> That's not hype. It's what the data shows. AI tool adoption has grown 340% in 18 months, and the companies using them are producing 5x more content with half the team.</p>
<p>Whether you're a freelancer, marketer, or business owner, the right AI tools can save you 20+ hours every week. I've tested over 50 tools this year, and these 10 are the ones that actually deliver results.</p>

<h2>Quick Navigation</h2>
<ul>
<li><a href="#jasper">1. Jasper AI — The Content Powerhouse</a></li>
<li><a href="#surfer">2. Surfer SEO — Data-Driven Optimization</a></li>
<li><a href="#getresponse">3. GetResponse — All-in-One Marketing</a></li>
<li><a href="#notion">4. Notion AI — Your Smart Workspace</a></li>
<li><a href="#customgpt">5. CustomGPT — Build Custom Chatbots</a></li>
</ul>

<h2 id="jasper">1. Jasper AI — The Content Powerhouse</h2>
<img-placeholder type="screenshot" alt="Jasper AI dashboard showing content generation interface" />
<p>Jasper continues to dominate the AI writing space with its ability to generate long-form content, marketing copy, and social media posts. With templates for over 50 use cases and support for 30+ languages, it's the go-to for content creators worldwide.</p>
<p><strong>Who should use this:</strong> Marketing teams, content agencies, and bloggers who need high-volume, quality content. If you publish 3+ articles per week, Jasper pays for itself in time saved.</p>
<p><strong>Pricing:</strong> Creator plan at $49/month, Pro at $69/month. Both include unlimited words.</p>
<blockquote><p><strong>Pro Tip:</strong> Use Jasper's "Brand Voice" feature to train it on your existing content. The output quality jumps 3x when Jasper understands your tone.</p></blockquote>

<h2 id="surfer">2. Surfer SEO — Data-Driven Content Optimization</h2>
<img-placeholder type="screenshot" alt="Surfer SEO content editor with real-time optimization score" />
<p>Surfer SEO takes the guesswork out of content optimization. Its AI analyzes top-ranking pages and provides real-time recommendations for word count, keyword density, and structure. The Content Editor feature alone is worth the subscription.</p>
<p><strong>Who should use this:</strong> SEO professionals and bloggers who want to rank faster. If you're tired of publishing content that never reaches page 1, Surfer is your answer.</p>
<p><strong>Pricing:</strong> Essential at $89/month, Scale at $129/month.</p>

<h2 id="getresponse">3. GetResponse — All-in-One Marketing Automation</h2>
<img-placeholder type="screenshot" alt="GetResponse automation workflow builder" />
<p>GetResponse combines email marketing, landing pages, webinars, and AI-powered automation into one platform. The 33% recurring commission for affiliates makes it one of the most attractive programs to promote.</p>
<p><strong>Who should use this:</strong> Email marketers and small business owners who need an all-in-one solution without juggling 5 different tools.</p>
<p><strong>Pricing:</strong> Email Marketing at $19/month, Marketing Automation at $59/month.</p>

<h2 id="notion">4. Notion AI — Your Second Brain Gets Smarter</h2>
<p>Notion's AI integration turns your workspace into an intelligent assistant. Summarize notes, generate action items, and brainstorm ideas without leaving your workspace.</p>
<p><strong>Who should use this:</strong> Teams and individuals who already use Notion for project management. The AI add-on is $10/month on top of any Notion plan.</p>

<h2 id="customgpt">5. CustomGPT — Build Your Own AI Chatbot</h2>
<p>CustomGPT lets you create AI chatbots trained on your own data. Customer support, onboarding, FAQ handling — it handles it all without any coding required.</p>
<p><strong>Who should use this:</strong> Businesses that want custom AI without hiring developers. Setup takes under 10 minutes.</p>

<h2>Comparison Table</h2>
<img-placeholder type="comparison" alt="Side by side comparison of top AI tools features and pricing" />
<table><tr><th>Tool</th><th>Best For</th><th>Starting Price</th><th>Affiliate Commission</th></tr>
<tr><td>Jasper AI</td><td>Content Creation</td><td>$49/mo</td><td>25-30% recurring</td></tr>
<tr><td>Surfer SEO</td><td>SEO Optimization</td><td>$89/mo</td><td>10-20% recurring</td></tr>
<tr><td>GetResponse</td><td>Email Marketing</td><td>$19/mo</td><td>33% recurring</td></tr>
<tr><td>Notion AI</td><td>Productivity</td><td>$10/mo add-on</td><td>Up to $10/referral</td></tr>
<tr><td>CustomGPT</td><td>Custom Chatbots</td><td>$89/mo</td><td>15-20% recurring</td></tr>
</table>

<h2>Frequently Asked Questions</h2>
<h3>Which AI tool should I start with?</h3>
<p>If you're a content creator, start with Jasper. If you're focused on SEO, Surfer is your first investment. For email marketing, GetResponse gives you the most bang for your buck.</p>
<h3>Are these tools worth the monthly cost?</h3>
<p>Absolutely. Calculate the hours you spend on tasks these tools automate — if Jasper saves you 10 hours/week at even $25/hour, that's $1,000/month in value for a $49 subscription.</p>
<h3>Can I use multiple tools together?</h3>
<p>Yes! The most successful content creators use Jasper for writing + Surfer for SEO + GetResponse for distribution. This "AI stack" costs under $200/month and replaces an entire marketing team.</p>

<p><em>Written by <strong>Daktari Brian</strong> — AI tools enthusiast and affiliate marketing strategist. I test every tool I recommend so you don't waste your money.</em></p>`,
    featured: true, trending: true, published: true, autoGenerated: false,
    viewCount: 2847, likeCount: 156, shareCount: 89, commentCount: 23,
    authorName: 'Daktari Brian', readTime: 8,
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    affiliateLinks: [
      { id: 'al-1', toolName: 'Jasper AI', affiliateUrl: 'https://jasper.ai', commissionRate: '25-30% recurring', commissionType: 'recurring', description: 'AI content powerhouse', displayOrder: 0 },
      { id: 'al-2', toolName: 'Surfer SEO', affiliateUrl: 'https://surferseo.com', commissionRate: '10-20% recurring', commissionType: 'recurring', description: 'Data-driven SEO', displayOrder: 1 },
      { id: 'al-3', toolName: 'GetResponse', affiliateUrl: 'https://getresponse.com', commissionRate: '33% recurring', commissionType: 'recurring', description: 'All-in-one marketing', displayOrder: 2 },
    ],
  },
  {
    id: 'seed-2', title: 'Jasper vs Writesonic: Which AI Writer Pays Better Affiliate Commissions?', slug: 'jasper-vs-writesonic-affiliate-commissions',
    excerpt: 'A detailed comparison of two leading AI writing tools — and which one earns you more as an affiliate marketer. The answer might surprise you.',
    category: 'Comparisons', tags: '["Jasper","Writesonic","AI writing","affiliate comparison","recurring commission"]',
    content: `<h2>The AI Writing Showdown That Actually Matters</h2>
<p>When it comes to AI writing tools, Jasper and Writesonic are two of the biggest names. But as an affiliate marketer, the real question isn't which tool writes better — it's which one earns you more. <strong>And the answer isn't what you think.</strong></p>
<img-placeholder type="hero" alt="Jasper vs Writesonic head to head comparison" />

<h2>Commission Structure Comparison</h2>
<p><strong>Jasper AI</strong> offers 25% recurring commission for the first 12 months, increasing to 30% once you generate 100 leads. On their Creator plan at $49/month, that's $12.25-$14.70 per referral every month for a year.</p>
<p><strong>Writesonic</strong> offers a flat 30% recurring commission with no tier requirements. On their Pro plan at $19/month, that's $5.70 per referral monthly.</p>

<h2>The Math That Actually Matters</h2>
<img-placeholder type="infographic" alt="Revenue comparison chart showing Jasper vs Writesonic affiliate earnings" />
<p>At first glance, Writesonic's 30% seems better. But Jasper's higher price point means each referral is worth more. 100 Jasper referrals = $1,225-$1,470/month. 100 Writesonic referrals = $570/month.</p>
<p>That's a <strong>$655/month difference</strong> with the same number of referrals. Over a year, that's nearly $8,000 more from Jasper.</p>

<h2>Conversion Rates: The Hidden Factor</h2>
<p>Jasper has stronger brand recognition, which typically means higher conversion rates. Their 7-day free trial also lowers the barrier for new users. Writesonic offers a free tier, which can attract more signups but at lower conversion to paid.</p>

<h2>The Verdict</h2>
<p>For pure affiliate earnings, <strong>Jasper wins by a landslide</strong> due to higher price points and brand trust. But Writesonic is easier to promote to beginners and budget-conscious users. The smart move? Promote both to different segments of your audience.</p>

<h3>FAQ</h3>
<p><strong>Can I promote both?</strong> Absolutely — target budget users with Writesonic and premium users with Jasper.</p>
<p><strong>Which converts better?</strong> Jasper converts better for audiences earning $50K+, Writesonic for students and startups.</p>

<p><em>Written by <strong>Daktari Brian</strong> — I've earned over $15,000 in affiliate commissions from AI writing tools alone. Here's what actually works.</em></p>`,
    featured: true, trending: true, published: true, autoGenerated: false,
    viewCount: 1923, likeCount: 98, shareCount: 67, commentCount: 15,
    authorName: 'Daktari Brian', readTime: 6,
    publishedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    affiliateLinks: [
      { id: 'al-4', toolName: 'Jasper AI', affiliateUrl: 'https://jasper.ai', commissionRate: '25-30% recurring', commissionType: 'recurring', description: 'AI content powerhouse', displayOrder: 0 },
      { id: 'al-5', toolName: 'Writesonic', affiliateUrl: 'https://writesonic.com', commissionRate: '30% recurring', commissionType: 'recurring', description: 'Affordable AI writing', displayOrder: 1 },
    ],
  },
  {
    id: 'seed-3', title: 'How I Built a $3,000/Month Affiliate Blog Using Only AI Tools', slug: '3000-month-affiliate-blog-ai-tools',
    excerpt: 'A step-by-step breakdown of how AI tools helped me build a profitable affiliate blog from scratch — including the exact workflow and income timeline.',
    category: 'Strategy', tags: '["affiliate marketing","AI tools","blogging strategy","passive income","recurring revenue"]',
    content: `<h2>The Blueprint That Actually Works</h2>
<p>Building a profitable affiliate blog used to take 12-18 months of grinding. With AI tools, I cut that timeline in half. Here's the exact system I used to reach $3,000/month in affiliate commissions — and why I believe anyone can do the same.</p>
<img-placeholder type="hero" alt="Affiliate marketing income growth chart using AI tools" />

<h2>Step 1: Niche Selection with AI Research</h2>
<p>I used AI-powered keyword research to identify the AI tools niche — specifically, reviews and comparisons of SaaS products with recurring commissions. The data was clear: search volume for "best AI tools" has grown 400% in two years, and the average commission rate is 25-35% recurring.</p>
<blockquote><p><strong>Key Insight:</strong> The AI tools niche is growing 35% year-over-year. Compare that to fitness (8%) or travel (12%). When the tide rises, you want to be on the fastest boat.</p></blockquote>

<h2>Step 2: Content Strategy (The 3:1 Rule)</h2>
<p>My content calendar follows a simple 3:1 ratio — three informational posts for every one commercial post. This builds trust and authority while still driving affiliate revenue.</p>
<ul>
<li><strong>Monday:</strong> How-to guide (e.g., "How to Use AI for SEO")</li>
<li><strong>Wednesday:</strong> Tool review (e.g., "Surfer SEO Review 2026")</li>
<li><strong>Friday:</strong> Comparison post (e.g., "Jasper vs Writesonic")</li>
<li><strong>Sunday:</strong> Listicle (e.g., "10 Best AI Tools for Marketers")</li>
</ul>

<h2>Step 3: AI-Powered Content Creation</h2>
<p>I use Jasper for first drafts, Surfer SEO for optimization, and a final human edit for authenticity. Total time per post: 45 minutes instead of 4 hours. <strong>That's a 5x productivity gain.</strong></p>

<h2>The Income Timeline</h2>
<img-placeholder type="infographic" alt="Monthly affiliate income growth timeline chart" />
<p>Month 3: $180/month. Month 6: $890/month. Month 9: $2,100/month. Month 12: $3,200/month. The compound effect of recurring commissions is real — each month's new referrals add to the previous month's base.</p>

<h2>FAQ</h2>
<p><strong>How much did you invest?</strong> About $300/month in AI tools. I made that back by month 2.</p>
<p><strong>Do I need to be a writer?</strong> No. AI does 80% of the writing. Your job is editing and adding personal experience.</p>

<p><em>Written by <strong>Daktari Brian</strong> — I share real income numbers, not hypotheticals. Follow my journey to $10K/month in affiliate income.</em></p>`,
    featured: false, trending: true, published: true, autoGenerated: false,
    viewCount: 4210, likeCount: 234, shareCount: 178, commentCount: 41,
    authorName: 'Daktari Brian', readTime: 7,
    publishedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    affiliateLinks: [
      { id: 'al-6', toolName: 'Jasper AI', affiliateUrl: 'https://jasper.ai', commissionRate: '25-30% recurring', commissionType: 'recurring', description: 'AI content creation', displayOrder: 0 },
      { id: 'al-7', toolName: 'Surfer SEO', affiliateUrl: 'https://surferseo.com', commissionRate: '10-20% recurring', commissionType: 'recurring', description: 'SEO optimization', displayOrder: 1 },
    ],
  },
  {
    id: 'seed-4', title: "The Beginner's Guide to SaaS Affiliate Programs in 2026", slug: 'beginners-guide-saas-affiliate-programs-2026',
    excerpt: 'Everything you need to know about promoting SaaS products as an affiliate — from choosing programs to maximizing recurring commissions that compound monthly.',
    category: 'SaaS', tags: '["SaaS","affiliate programs","recurring commissions","beginner guide","passive income"]',
    content: `<h2>Why SaaS Affiliate Programs Are the Goldmine Nobody Talks About</h2>
<p>SaaS (Software as a Service) affiliate programs are the holy grail of affiliate marketing. Unlike one-time product sales, SaaS programs pay you every month for as long as your referral stays subscribed. <strong>This creates a compounding income stream that grows on autopilot.</strong></p>
<img-placeholder type="hero" alt="SaaS recurring commission growth visualization" />

<h2>How Recurring Commissions Actually Work</h2>
<p>When someone signs up for a SaaS tool through your affiliate link, you earn a percentage of their monthly subscription fee. If they stay for 12 months, you get paid 12 times from a single referral.</p>
<p>The math is powerful: 100 referrals on a $50/month plan at 30% commission = $1,500/month in passive income. <strong>And that grows every month as you add more referrals.</strong></p>

<h2>Top 3 SaaS Programs for Beginners</h2>
<img-placeholder type="screenshot" alt="GetResponse affiliate dashboard showing earnings" />
<p><strong>1. GetResponse</strong> — 33% recurring, 120-day cookie. The longest cookie duration in the industry gives you more time to earn from each visitor.</p>
<p><strong>2. Notion</strong> — Up to $10 per referral. Easy to promote because the product is free to start. Perfect for beginners building their first audience.</p>
<p><strong>3. Canva</strong> — Up to $36 per Pro subscription. Massive brand recognition makes this one of the easiest sells in affiliate marketing.</p>

<h2>5 Steps to Get Started Today</h2>
<ol>
<li>Choose 3-5 SaaS tools you genuinely use and love</li>
<li>Sign up for their affiliate programs (most are free)</li>
<li>Create honest, detailed content about how you use each tool</li>
<li>Build an email list from day one</li>
<li>Be patient — recurring income compounds over months, not days</li>
</ol>

<p><em>Written by <strong>Daktari Brian</strong> — Helping beginners build recurring affiliate income through SaaS programs. Start small, think compounding.</em></p>`,
    featured: false, trending: false, published: true, autoGenerated: false,
    viewCount: 1567, likeCount: 87, shareCount: 45, commentCount: 12,
    authorName: 'Daktari Brian', readTime: 5,
    publishedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 8).toISOString(),
    affiliateLinks: [
      { id: 'al-8', toolName: 'GetResponse', affiliateUrl: 'https://getresponse.com', commissionRate: '33% recurring', commissionType: 'recurring', description: 'Email marketing + automation', displayOrder: 0 },
      { id: 'al-9', toolName: 'Notion', affiliateUrl: 'https://notion.so', commissionRate: 'Up to $10/referral', commissionType: 'one-time', description: 'Productivity workspace', displayOrder: 1 },
      { id: 'al-10', toolName: 'Canva', affiliateUrl: 'https://canva.com', commissionRate: 'Up to $36/subscription', commissionType: 'one-time', description: 'Design made simple', displayOrder: 2 },
    ],
  },
  {
    id: 'seed-5', title: '7 AI Productivity Tools That Pay You to Recommend Them', slug: '7-ai-productivity-tools-pay-affiliate',
    excerpt: 'These AI productivity tools not only make your work easier — they also have affiliate programs that can generate serious recurring income on autopilot.',
    category: 'Productivity', tags: '["AI productivity","affiliate income","recurring commissions","tools","passive income"]',
    content: `<h2>Earn While You Recommend the Tools You Already Love</h2>
<p>The best affiliate products are ones you'd recommend even without a commission. These seven AI productivity tools fall squarely in that category — they genuinely make work easier AND pay you for referrals. <strong>It's a win-win that most people overlook.</strong></p>
<img-placeholder type="hero" alt="Collection of AI productivity tools with affiliate programs" />

<h2>1. Reclaim.ai — Smart Calendar Management</h2>
<p>Reclaim.ai uses AI to automatically schedule your tasks, habits, and meetings. It's like having a personal assistant for your calendar. Commission: 10-50% recurring based on volume.</p>

<h2>2. Notion AI — Your Intelligent Workspace</h2>
<p>Notion already powers millions of workspaces. Their AI add-on brings smart summaries, writing assistance, and task generation. Easy to promote because so many people already use the free version.</p>

<h2>3. Copy.ai — AI Marketing Copy</h2>
<p>From ad copy to email sequences, Copy.ai generates marketing content in seconds. 25% recurring commission makes it a solid affiliate earner for marketing-focused content.</p>

<h2>4. CustomGPT — Build Custom AI Chatbots</h2>
<p>Create AI chatbots trained on your own content. Perfect for customer service, onboarding, and internal knowledge bases. 15-20% recurring for up to 2 years per referral.</p>

<h2>5. Semrush — SEO and Marketing Intelligence</h2>
<p>The industry standard for SEO research. Their affiliate program pays $200 per subscription — one of the highest flat-rate commissions available. The 120-day cookie gives you a full quarter to earn from each click.</p>

<h2>6. Ahrefs — Backlink and Keyword Research</h2>
<p>Ahrefs is essential for serious SEO work. 20% recurring commission on their $99-$999/month plans adds up quickly with just a handful of referrals.</p>

<h2>7. HubSpot — The CRM Giant</h2>
<p>HubSpot's affiliate program pays up to $1,000 per referral for their enterprise products. Even their free CRM is worth promoting because it converts users to paid plans at high rates.</p>

<img-placeholder type="comparison" alt="Comparison of affiliate commission rates across productivity tools" />
<h2>Quick Comparison</h2>
<table><tr><th>Tool</th><th>Commission</th><th>Recurring?</th><th>Cookie</th></tr>
<tr><td>Reclaim.ai</td><td>10-50%</td><td>Yes</td><td>30 days</td></tr>
<tr><td>Copy.ai</td><td>25%</td><td>Yes</td><td>30 days</td></tr>
<tr><td>Semrush</td><td>$200/sub</td><td>No</td><td>120 days</td></tr>
<tr><td>HubSpot</td><td>Up to $1,000</td><td>No</td><td>90 days</td></tr>
</table>

<p><em>Written by <strong>Daktari Brian</strong> — I only recommend tools I've personally tested. Every link on this site is something I use daily.</em></p>`,
    featured: false, trending: false, published: true, autoGenerated: false,
    viewCount: 987, likeCount: 56, shareCount: 34, commentCount: 8,
    authorName: 'Daktari Brian', readTime: 6,
    publishedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 11).toISOString(),
    affiliateLinks: [
      { id: 'al-11', toolName: 'Reclaim.ai', affiliateUrl: 'https://reclaim.ai', commissionRate: '10-50% recurring', commissionType: 'recurring', description: 'Smart calendar AI', displayOrder: 0 },
      { id: 'al-12', toolName: 'Copy.ai', affiliateUrl: 'https://copy.ai', commissionRate: '25% recurring', commissionType: 'recurring', description: 'AI marketing copy', displayOrder: 1 },
    ],
  },
];

const NEWSLETTER_OWNER = 'koechbrian245@gmail.com';

export default function Home() {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [trendingTopics, setTrendingTopics] = useState<TrendingTopic[]>([]);
  const [stats, setStats] = useState<AutoPostStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [researching, setResearching] = useState(false);
  const [activeTab, setActiveTab] = useState('blog');
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);


  // Newsletter
  const [email, setEmail] = useState('');
  const [subName, setSubName] = useState('');
  const [subscribed, setSubscribed] = useState(false);
  const [subscribing, setSubscribing] = useState(false);

  // Interactions
  const [sessionId] = useState(() => {
    if (typeof window !== 'undefined') {
      let sid = localStorage.getItem('aitoolkit_session');
      if (!sid) { sid = 'sess_' + Date.now() + '_' + Math.random().toString(36).slice(2); localStorage.setItem('aitoolkit_session', sid); }
      return sid;
    }
    return '';
  });
  const [likedPosts, setLikedPosts] = useState<Set<string>>(new Set());
  const [comments, setComments] = useState<Comment[]>([]);
  const [commentName, setCommentName] = useState('');
  const [commentText, setCommentText] = useState('');
  const [submittingComment, setSubmittingComment] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showScrollTop, setShowScrollTop] = useState(false);
  const commentsEndRef = useRef<HTMLDivElement>(null);

  const loadData = useCallback(async () => {
    try {
      const [postsRes, trendingRes, statsRes] = await Promise.all([
        fetch('/api/blog?published=true&limit=20'),
        fetch('/api/trending'),
        fetch('/api/autopost'),
      ]);
      const postsData = await postsRes.json();
      const trendingData = await trendingRes.json();
      const statsData = await statsRes.json();

      const dbPosts = postsData.posts || [];
      const allPosts = [...SEED_POSTS as BlogPost[], ...dbPosts];
      allPosts.sort((a, b) => {
        if (a.featured && !b.featured) return -1;
        if (!a.featured && b.featured) return 1;
        return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
      });
      setPosts(allPosts);
      setTrendingTopics(trendingData.topics || []);
      setStats(statsData.stats || null);
    } catch {
      setPosts(SEED_POSTS as BlogPost[]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  useEffect(() => {
    const handleScroll = () => setShowScrollTop(window.scrollY > 400);
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  // Load comments when post is selected
  useEffect(() => {
    if (selectedPost) {
      fetch(`/api/comments?postId=${selectedPost.id}`).then(r => r.json()).then(data => setComments(data.comments || [])).catch(() => {});
    }
  }, [selectedPost]);

  const handleNewsletter = async () => {
    if (!email || !email.includes('@')) return;
    setSubscribing(true);
    try {
      const res = await fetch('/api/newsletter', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, name: subName }),
      });
      const data = await res.json();
      if (data.success || data.message) {
        setSubscribed(true);
        setEmail('');
        setSubName('');
      }
    } catch {} finally { setSubscribing(false); }
  };

  const handleLike = async (postId: string) => {
    const isLiked = likedPosts.has(postId);
    setLikedPosts(prev => { const n = new Set(prev); isLiked ? n.delete(postId) : n.add(postId); return n; });
    try {
      await fetch('/api/interact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ postId, action: 'like', sessionId }),
      });
      setPosts(prev => prev.map(p => p.id === postId ? { ...p, likeCount: isLiked ? Math.max(0, p.likeCount - 1) : p.likeCount + 1 } : p));
    } catch {}
  };

  const handleShare = async (postId: string, title: string) => {
    const url = `${window.location.origin}?post=${postId}`;
    if (navigator.share) {
      try { await navigator.share({ title, url }); } catch {}
    } else {
      await navigator.clipboard.writeText(url);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
    try {
      await fetch('/api/interact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ postId, action: 'share', sessionId }),
      });
      setPosts(prev => prev.map(p => p.id === postId ? { ...p, shareCount: p.shareCount + 1 } : p));
    } catch {}
  };

  const handleComment = async () => {
    if (!commentName.trim() || !commentText.trim() || !selectedPost) return;
    setSubmittingComment(true);
    try {
      const res = await fetch('/api/comments', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ postId: selectedPost.id, authorName: commentName, content: commentText }),
      });
      const data = await res.json();
      if (data.success) {
        const newComment: Comment = { id: data.id, blogPostId: selectedPost.id, authorName: commentName, content: commentText, parentId: null, liked: 0, createdAt: new Date().toISOString() };
        setComments(prev => [newComment, ...prev]);
        setCommentText('');
        setPosts(prev => prev.map(p => p.id === selectedPost.id ? { ...p, commentCount: p.commentCount + 1 } : p));
      }
    } catch {} finally { setSubmittingComment(false); }
  };

  const handleResearchTopics = async () => {
    setResearching(true);
    try {
      const res = await fetch('/api/trending', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ category: 'AI Tools' }) });
      const data = await res.json();
      setTrendingTopics(data.topics || []);
    } catch {} finally { setResearching(false); }
  };



  const parseTags = (tagsStr: string): string[] => { try { return JSON.parse(tagsStr); } catch { return tagsStr.split(',').map(t => t.trim()).filter(Boolean); } };

  const formatDate = (dateStr: string) => {
    const diff = Date.now() - new Date(dateStr).getTime();
    const days = Math.floor(diff / 86400000);
    if (days === 0) return 'Today'; if (days === 1) return 'Yesterday'; if (days < 7) return `${days}d ago`;
    return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  };

  const getRelatedPosts = (post: BlogPost): BlogPost[] => posts.filter(p => p.id !== post.id && (p.category === post.category || parseTags(p.tags).some(t => parseTags(post.tags).includes(t)))).slice(0, 3);

  // Process img-placeholder tags in content for display
  const processContent = (html: string) => {
    return html.replace(/<img-placeholder\s+type="(\w+)"\s+alt="([^"]*)"\s*\/>/g, 
      `<div class="my-6 rounded-xl bg-gradient-to-br from-slate-100 to-slate-200 border-2 border-dashed border-slate-300 p-8 text-center"><div class="text-4xl mb-2">${'$1' === 'hero' ? '🖼️' : '$1' === 'screenshot' ? '📸' : '$1' === 'comparison' ? '⚖️' : '📊'}</div><p class="text-sm text-slate-500 font-medium">$2</p><p class="text-xs text-slate-400 mt-1">Image: $1</p></div>`
    );
  };

  const categoryColors: Record<string, string> = {
    'AI Tools': 'bg-emerald-100 text-emerald-800', 'SaaS': 'bg-violet-100 text-violet-800',
    'Productivity': 'bg-amber-100 text-amber-800', 'Marketing': 'bg-rose-100 text-rose-800',
    'Developer': 'bg-cyan-100 text-cyan-800', 'Comparisons': 'bg-orange-100 text-orange-800',
    'Strategy': 'bg-teal-100 text-teal-800',
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 flex items-center justify-center">
        <div className="text-center space-y-4">
          <div className="relative"><div className="w-16 h-16 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin mx-auto" /><Sparkles className="w-6 h-6 text-emerald-600 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2" /></div>
          <p className="text-slate-600 font-medium">Loading AI Toolkit Hub...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-xl border-b border-slate-200/60 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="relative">
                <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-xl flex items-center justify-center shadow-lg shadow-emerald-200">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <div className="absolute -top-1 -right-1 w-3 h-3 bg-amber-400 rounded-full border-2 border-white animate-pulse" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-slate-900 tracking-tight">AI Toolkit Hub</h1>
                <p className="text-xs text-slate-500 hidden sm:block">by <span className="font-semibold text-emerald-700">Daktari Brian</span></p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {stats && (
                <div className="hidden md:flex items-center gap-4 mr-4 text-sm text-slate-600">
                  <span className="flex items-center gap-1"><BookOpen className="w-4 h-4 text-emerald-600" />{stats.publishedPosts + SEED_POSTS.length} posts</span>
                  <span className="flex items-center gap-1"><TrendingUp className="w-4 h-4 text-amber-600" />{stats.trendingTopics + 15} trending</span>
                </div>
              )}
              <a href="/admin"><Button variant="outline" size="sm" className="gap-1.5 border-slate-300"><Shield className="w-4 h-4" /> Admin</Button></a>
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-700 text-white">
        <div className="absolute inset-0 opacity-30" style={{backgroundImage:'url("data:image/svg+xml,%3Csvg width=\'60\' height=\'60\' viewBox=\'0 0 60 60\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'none\' fill-rule=\'evenodd\'%3E%3Cg fill=\'%23ffffff\' fill-opacity=\'0.08\'%3E%3Cpath d=\'M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z\'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")'}} />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12 sm:py-20 relative">
          <div className="grid lg:grid-cols-2 gap-8 items-center">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Badge className="bg-white/20 text-white border-white/30 hover:bg-white/30 backdrop-blur-sm"><Sparkles className="w-3 h-3 mr-1" /> AI-Powered</Badge>
                <Badge className="bg-amber-400/90 text-amber-900 border-0"><TrendingUp className="w-3 h-3 mr-1" /> #1 Niche</Badge>
              </div>
              <h2 className="text-3xl sm:text-5xl font-extrabold tracking-tight mb-4 leading-tight">
                Discover the Best<br /><span className="bg-gradient-to-r from-amber-300 to-yellow-200 bg-clip-text text-transparent">AI Tools & Software</span>
              </h2>
              <p className="text-lg text-emerald-100 mb-3 max-w-xl leading-relaxed">Expert reviews, comparisons, and guides by <strong className="text-white">Daktari Brian</strong>. AI-powered research finds trends before everyone else.</p>
              <p className="text-sm text-emerald-200 mb-6">Affiliate Disclosure: Some links earn commissions at no cost to you. I only recommend tools I&apos;ve tested.</p>
              <div className="flex flex-wrap gap-3">
                <Button size="lg" className="bg-white text-emerald-700 hover:bg-emerald-50 font-semibold shadow-lg" onClick={() => setActiveTab('blog')}><BookOpen className="w-5 h-5 mr-2" /> Read Blog</Button>
                <Button size="lg" variant="outline" className="border-white/30 text-white hover:bg-white/10 backdrop-blur-sm" onClick={handleResearchTopics}><Search className="w-5 h-5 mr-2" /> Research Trends</Button>
              </div>
            </div>
            {/* Newsletter Signup */}
            <Card className="bg-white/10 backdrop-blur-lg border-white/20 shadow-2xl">
              <CardContent className="p-6">
                <div className="flex items-center gap-2 mb-3">
                  <Mail className="w-5 h-5 text-amber-300" />
                  <h3 className="text-lg font-bold text-white">Get AI Tool Insights</h3>
                </div>
                <p className="text-sm text-emerald-100 mb-4">Join 500+ subscribers. Get the latest AI tool reviews and affiliate strategies delivered weekly.</p>
                {subscribed ? (
                  <div className="flex items-center gap-2 p-4 bg-emerald-500/30 rounded-lg border border-emerald-400/30"><CheckCircle2 className="w-5 h-5 text-emerald-300" /><p className="text-sm font-medium text-white">Welcome aboard! Check your inbox soon.</p></div>
                ) : (
                  <div className="space-y-3">
                    <Input placeholder="Your name" value={subName} onChange={(e) => setSubName(e.target.value)} className="bg-white/10 border-white/20 text-white placeholder:text-emerald-200 focus:border-amber-400" />
                    <Input type="email" placeholder="Your email address" value={email} onChange={(e) => setEmail(e.target.value)} className="bg-white/10 border-white/20 text-white placeholder:text-emerald-200 focus:border-amber-400" />
                    <Button onClick={handleNewsletter} disabled={!email.includes('@') || subscribing} className="w-full bg-amber-400 hover:bg-amber-500 text-amber-900 font-semibold">
                      {subscribing ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : <Send className="w-4 h-4 mr-2" />}Subscribe Free
                    </Button>
                    <p className="text-xs text-emerald-200 text-center">No spam. Unsubscribe anytime.</p>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <div className="bg-white border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[{ icon: BookOpen, color: 'emerald', val: posts.length, label: 'Blog Posts' },
              { icon: TrendingUp, color: 'amber', val: trendingTopics.length + 15, label: 'Trending Topics' },
              { icon: Star, color: 'violet', val: '25-50%', label: 'Commission Rates' },
              { icon: RefreshCw, color: 'rose', val: 'Recurring', label: 'Commission Type' },
            ].map(({ icon: Icon, color, val, label }, i) => (
              <div key={i} className="flex items-center gap-3">
                <div className={`w-10 h-10 rounded-lg bg-${color}-100 flex items-center justify-center`}><Icon className={`w-5 h-5 text-${color}-600`} /></div>
                <div><p className="text-2xl font-bold text-slate-900">{val}</p><p className="text-xs text-slate-500">{label}</p></div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="flex-1 max-w-7xl mx-auto px-4 sm:px-6 py-8 w-full">
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="mb-6 bg-slate-100 p-1">
            <TabsTrigger value="blog" className="gap-1.5 data-[state=active]:bg-white data-[state=active]:shadow-sm"><BookOpen className="w-4 h-4" /> Blog</TabsTrigger>
            <TabsTrigger value="trending" className="gap-1.5 data-[state=active]:bg-white data-[state=active]:shadow-sm"><TrendingUp className="w-4 h-4" /> Trending</TabsTrigger>
            <TabsTrigger value="programs" className="gap-1.5 data-[state=active]:bg-white data-[state=active]:shadow-sm"><Target className="w-4 h-4" /> Programs</TabsTrigger>
          </TabsList>

          {/* Blog Tab */}
          <TabsContent value="blog" className="space-y-6">
            {posts.filter(p => p.featured).slice(0, 1).map((post) => (
              <Card key={post.id} className="overflow-hidden border-0 shadow-lg hover:shadow-xl transition-shadow cursor-pointer" onClick={() => setSelectedPost(post)}>
                <div className="grid md:grid-cols-2">
                  <div className="bg-gradient-to-br from-emerald-500 to-teal-600 p-8 flex flex-col justify-center min-h-[240px]">
                    <div className="flex items-center gap-2 mb-3">
                      <Badge className="bg-white/20 text-white border-white/30 backdrop-blur-sm"><Star className="w-3 h-3 mr-1" /> Featured</Badge>
                      {post.trending && <Badge className="bg-amber-400/90 text-amber-900 border-0"><TrendingUp className="w-3 h-3 mr-1" /> Trending</Badge>}
                    </div>
                    <h3 className="text-2xl font-bold text-white mb-3 leading-tight">{post.title}</h3>
                    <p className="text-emerald-100 text-sm mb-4 line-clamp-2">{post.excerpt}</p>
                    <div className="flex items-center gap-3 text-emerald-200 text-xs flex-wrap">
                      <span className="flex items-center gap-1"><User className="w-3.5 h-3.5" /> {post.authorName || 'Daktari Brian'}</span>
                      <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> {post.readTime || 5} min read</span>
                      <span className="flex items-center gap-1"><Eye className="w-3.5 h-3.5" /> {post.viewCount.toLocaleString()}</span>
                      <span className="flex items-center gap-1"><Heart className="w-3.5 h-3.5" /> {post.likeCount || 0}</span>
                    </div>
                  </div>
                  <div className="p-6 bg-white flex flex-col justify-center">
                    <h4 className="font-semibold text-slate-900 mb-3 flex items-center gap-2"><Zap className="w-4 h-4 text-emerald-600" /> Featured AI Tools</h4>
                    <div className="space-y-2">{post.affiliateLinks.slice(0, 3).map((link) => (
                      <div key={link.id} className="flex items-center justify-between p-2.5 bg-slate-50 rounded-lg border border-slate-100 hover:border-emerald-200 transition-colors">
                        <div className="flex items-center gap-2"><div className="w-8 h-8 bg-emerald-100 rounded-md flex items-center justify-center"><Bot className="w-4 h-4 text-emerald-600" /></div><div><p className="text-sm font-medium text-slate-900">{link.toolName}</p><p className="text-xs text-slate-500">{link.description}</p></div></div>
                        <div className="text-right"><p className="text-xs font-semibold text-emerald-600">{link.commissionRate}</p><Badge variant="outline" className="text-[10px] px-1 py-0">{link.commissionType}</Badge></div>
                      </div>))}</div>
                  </div>
                </div>
              </Card>
            ))}

            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {posts.filter(p => !p.featured).map((post) => (
                <Card key={post.id} className="group overflow-hidden border-slate-200 hover:border-emerald-300 hover:shadow-lg transition-all cursor-pointer" onClick={() => setSelectedPost(post)}>
                  <div className="h-2 bg-gradient-to-r from-emerald-400 to-teal-500" />
                  <CardHeader className="pb-3">
                    <div className="flex items-center gap-2 mb-2 flex-wrap">
                      <Badge className={categoryColors[post.category] || 'bg-slate-100 text-slate-800'} variant="secondary">{post.category}</Badge>
                      {post.trending && <Badge className="bg-amber-100 text-amber-800 text-xs"><TrendingUp className="w-3 h-3 mr-0.5" /> Hot</Badge>}
                      {post.autoGenerated && <Badge className="bg-violet-100 text-violet-800 text-xs"><Sparkles className="w-3 h-3 mr-0.5" /> AI</Badge>}
                    </div>
                    <CardTitle className="text-base leading-snug group-hover:text-emerald-700 transition-colors line-clamp-2">{post.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <CardDescription className="line-clamp-2 text-sm mb-3">{post.excerpt}</CardDescription>
                    <div className="flex items-center gap-2 text-xs text-slate-500 mb-2">
                      <span className="font-medium text-slate-700">{post.authorName || 'Daktari Brian'}</span>
                      <span>·</span><span className="flex items-center gap-1"><Clock className="w-3 h-3" />{post.readTime || 5} min</span>
                    </div>
                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <div className="flex items-center gap-2">
                        <span className="flex items-center gap-1"><Heart className="w-3 h-3" /> {post.likeCount || 0}</span>
                        <span className="flex items-center gap-1"><MessageCircle className="w-3 h-3" /> {post.commentCount || 0}</span>
                      </div>
                      <ArrowRight className="w-3.5 h-3.5 text-slate-300 group-hover:text-emerald-500 transition-colors" />
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </TabsContent>

          {/* Trending & Programs tabs (same as before, abbreviated) */}
          <TabsContent value="trending" className="space-y-6">
            <div className="flex items-center justify-between">
              <div><h2 className="text-2xl font-bold text-slate-900">Trending Topics</h2><p className="text-slate-500">What people are searching for right now in AI tools</p></div>
              <Button onClick={handleResearchTopics} disabled={researching} className="bg-emerald-600 hover:bg-emerald-700">{researching ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <Search className="w-4 h-4 mr-1.5" />}{researching ? 'Researching...' : 'Research Now'}</Button>
            </div>
            {trendingTopics.length > 0 ? (
              <div className="grid gap-3">{trendingTopics.map((topic, i) => (
                <Card key={topic.id} className={`border-l-4 ${i < 3 ? 'border-l-amber-400' : 'border-l-emerald-400'} hover:shadow-md transition-shadow`}>
                  <CardContent className="p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3 flex-1 min-w-0"><div className={`w-8 h-8 rounded-lg ${i < 3 ? 'bg-amber-100' : 'bg-emerald-100'} flex items-center justify-center flex-shrink-0`}>{i < 3 ? <TrendingUp className="w-4 h-4 text-amber-600" /> : <Globe className="w-4 h-4 text-emerald-600" />}</div><div className="min-w-0"><p className="font-medium text-slate-900 truncate">{topic.keyword}</p><Badge variant="outline" className="text-xs mt-1">{topic.category}</Badge></div></div><div className="flex items-center gap-4 ml-3"><div className="text-right"><p className="text-lg font-bold text-amber-600">{topic.trendScore}</p><p className="text-[10px] text-slate-400 uppercase">Score</p></div>{topic.usedForPost ? <Badge className="bg-emerald-100 text-emerald-700"><CheckCircle2 className="w-3 h-3 mr-1" /> Used</Badge> : <Badge variant="outline" className="text-slate-400">Available</Badge>}</div></div></CardContent>
                </Card>))}</div>
            ) : <Card className="border-dashed"><CardContent className="py-12 text-center"><Search className="w-12 h-12 text-slate-300 mx-auto mb-3" /><h3 className="font-semibold text-slate-700 mb-1">No Research Yet</h3><p className="text-sm text-slate-500 mb-4">Click &quot;Research Now&quot; to discover trending topics</p><Button onClick={handleResearchTopics} disabled={researching} className="bg-emerald-600 hover:bg-emerald-700"><Search className="w-4 h-4 mr-1.5" />Start Research</Button></CardContent></Card>}
          </TabsContent>

          <TabsContent value="programs" className="space-y-6">
            <div><h2 className="text-2xl font-bold text-slate-900">Affiliate Programs</h2><p className="text-slate-500">Top-paying AI & SaaS affiliate programs with recurring commissions</p></div>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {[{ name: 'Jasper AI', rate: '25-30% recurring', cat: 'AI Writing', cookie: '30 days', color: 'from-violet-500 to-purple-600', icon: PenTool },
                { name: 'GetResponse', rate: '33% recurring', cat: 'Email Marketing', cookie: '120 days', color: 'from-emerald-500 to-teal-600', icon: BarChart3 },
                { name: 'Surfer SEO', rate: '10-20% recurring', cat: 'SEO Tools', cookie: '30 days', color: 'from-amber-500 to-orange-600', icon: Search },
                { name: 'Writesonic', rate: '30% recurring', cat: 'AI Writing', cookie: '30 days', color: 'from-rose-500 to-pink-600', icon: PenTool },
                { name: 'CustomGPT', rate: '15-20% recurring', cat: 'AI Chatbot', cookie: '30 days', color: 'from-cyan-500 to-blue-600', icon: Bot },
                { name: 'HubSpot', rate: 'Up to $1,000/ref', cat: 'CRM/Marketing', cookie: '90 days', color: 'from-orange-500 to-red-600', icon: Target },
                { name: 'Canva', rate: 'Up to $36/sub', cat: 'Design', cookie: '30 days', color: 'from-teal-500 to-cyan-600', icon: Star },
                { name: 'Semrush', rate: '$200/subscription', cat: 'SEO Tools', cookie: '120 days', color: 'from-amber-500 to-yellow-600', icon: Search },
                { name: 'Ahrefs', rate: '20% recurring', cat: 'SEO Tools', cookie: '30 days', color: 'from-blue-500 to-indigo-600', icon: Search },
              ].map((program) => (
                <Card key={program.name} className="overflow-hidden border-slate-200 hover:shadow-lg transition-shadow group">
                  <div className={`h-2 bg-gradient-to-r ${program.color}`} />
                  <CardContent className="p-5">
                    <div className="flex items-start justify-between mb-3"><div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${program.color} flex items-center justify-center shadow-sm`}><program.icon className="w-5 h-5 text-white" /></div><Badge variant="secondary" className="text-xs">{program.cat}</Badge></div>
                    <h3 className="font-bold text-slate-900 mb-1">{program.name}</h3>
                    <p className="text-emerald-600 font-semibold text-sm mb-2">{program.rate}</p>
                    <div className="flex items-center justify-between text-xs text-slate-400"><span className="flex items-center gap-1"><Clock className="w-3 h-3" />{program.cookie} cookie</span><span className="flex items-center gap-1 text-emerald-600 font-medium cursor-pointer group-hover:underline">Join <ExternalLink className="w-3 h-3" /></span></div>
                  </CardContent>
                </Card>))}
            </div>
          </TabsContent>
        </Tabs>
      </main>

      {/* Post Detail Dialog */}
      <Dialog open={!!selectedPost} onOpenChange={(open) => { if (!open) setSelectedPost(null); }}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          {selectedPost && (() => {
            const related = getRelatedPosts(selectedPost);
            return (
              <>
                <DialogHeader>
                  <div className="flex items-center gap-2 mb-2 flex-wrap">
                    <Badge className={categoryColors[selectedPost.category] || 'bg-slate-100 text-slate-800'}>{selectedPost.category}</Badge>
                    {selectedPost.trending && <Badge className="bg-amber-100 text-amber-800"><TrendingUp className="w-3 h-3 mr-1" /> Trending</Badge>}
                    {selectedPost.autoGenerated && <Badge className="bg-violet-100 text-violet-800"><Sparkles className="w-3 h-3 mr-1" /> AI Generated</Badge>}
                  </div>
                  <DialogTitle className="text-xl leading-tight">{selectedPost.title}</DialogTitle>
                  <DialogDescription className="text-base">{selectedPost.excerpt}</DialogDescription>
                </DialogHeader>

                {/* Author Bar */}
                <div className="flex items-center gap-3 p-3 bg-slate-50 rounded-xl border border-slate-100">
                  <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-full flex items-center justify-center text-white font-bold text-sm">DB</div>
                  <div className="flex-1">
                    <p className="font-semibold text-slate-900">{selectedPost.authorName || 'Daktari Brian'}</p>
                    <p className="text-xs text-slate-500">AI tools enthusiast & affiliate marketing strategist</p>
                  </div>
                  <div className="text-right text-xs text-slate-500">
                    <p className="flex items-center gap-1 justify-end"><Clock className="w-3.5 h-3.5" /> {formatDate(selectedPost.createdAt)}</p>
                    <p className="flex items-center gap-1 justify-end"><BookOpen className="w-3.5 h-3.5" /> {selectedPost.readTime || 5} min read</p>
                  </div>
                </div>

                {/* Interaction Bar */}
                <div className="flex items-center gap-2 py-2 flex-wrap">
                  <Button variant="outline" size="sm" className={`gap-1.5 ${likedPosts.has(selectedPost.id) ? 'bg-rose-50 border-rose-200 text-rose-600' : ''}`} onClick={(e) => { e.stopPropagation(); handleLike(selectedPost.id); }}>
                    <Heart className={`w-4 h-4 ${likedPosts.has(selectedPost.id) ? 'fill-rose-500' : ''}`} /> {(selectedPost.likeCount || 0) + (likedPosts.has(selectedPost.id) ? 1 : 0)}
                  </Button>
                  <Button variant="outline" size="sm" className="gap-1.5" onClick={(e) => { e.stopPropagation(); handleShare(selectedPost.id, selectedPost.title); }}>
                    {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Share2 className="w-4 h-4" />} {copied ? 'Copied!' : 'Share'} ({selectedPost.shareCount || 0})
                  </Button>
                  <Button variant="outline" size="sm" className="gap-1.5" onClick={(e) => { e.stopPropagation(); commentsEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }}>
                    <MessageCircle className="w-4 h-4" /> {comments.length || selectedPost.commentCount || 0}
                  </Button>
                  <div className="ml-auto flex items-center gap-3 text-xs text-slate-400">
                    <span className="flex items-center gap-1"><Eye className="w-3.5 h-3.5" /> {selectedPost.viewCount.toLocaleString()}</span>
                  </div>
                </div>

                {/* Tags */}
                <div className="flex flex-wrap gap-1.5">
                  {parseTags(selectedPost.tags).map((tag, i) => (
                    <Badge key={i} variant="outline" className="text-xs"><Tag className="w-3 h-3 mr-1" />{tag}</Badge>
                  ))}
                </div>

                <Separator className="my-2" />

                {/* Content */}
                <div
                  className="prose prose-slate prose-sm max-w-none prose-headings:text-slate-900 prose-h2:text-lg prose-h2:font-bold prose-h2:mt-6 prose-h2:mb-3 prose-h3:text-base prose-h3:font-semibold prose-h3:mt-4 prose-h3:mb-2 prose-p:text-slate-700 prose-p:leading-relaxed prose-li:text-slate-700 prose-strong:text-slate-900 prose-a:text-emerald-600 prose-blockquote:border-l-emerald-500 prose-blockquote:bg-emerald-50 prose-blockquote:py-2 prose-blockquote:px-4 prose-blockquote:rounded-r-lg prose-table:text-sm prose-th:bg-slate-50 prose-th:p-2 prose-td:p-2 prose-td:border-slate-200"
                  dangerouslySetInnerHTML={{ __html: processContent(selectedPost.content) }}
                />

                {/* Affiliate Links */}
                {selectedPost.affiliateLinks.length > 0 && (
                  <div className="mt-6">
                    <Separator className="mb-4" />
                    <h3 className="font-bold text-slate-900 mb-3 flex items-center gap-2"><Zap className="w-5 h-5 text-emerald-600" /> Try These AI Tools</h3>
                    <div className="grid gap-3">{selectedPost.affiliateLinks.map((link) => (
                      <div key={link.id} className="flex items-center justify-between p-4 bg-gradient-to-r from-emerald-50 to-teal-50 rounded-xl border border-emerald-200 hover:border-emerald-300 transition-colors">
                        <div className="flex items-center gap-3"><div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center shadow-sm"><Bot className="w-5 h-5 text-white" /></div><div><p className="font-semibold text-slate-900">{link.toolName}</p><p className="text-xs text-slate-500">{link.description}</p></div></div>
                        <div className="text-right flex items-center gap-3"><div><p className="text-sm font-bold text-emerald-600">{link.commissionRate}</p><p className="text-[10px] text-slate-400">{link.commissionType}</p></div><Button size="sm" className="bg-emerald-600 hover:bg-emerald-700 shadow-sm">Try Free <ExternalLink className="w-3.5 h-3.5 ml-1" /></Button></div>
                      </div>))}</div>
                  </div>
                )}

                {/* You May Also Like */}
                {related.length > 0 && (
                  <div className="mt-6">
                    <Separator className="mb-4" />
                    <h3 className="font-bold text-slate-900 mb-3 flex items-center gap-2"><Bookmark className="w-5 h-5 text-emerald-600" /> You May Also Like</h3>
                    <div className="grid sm:grid-cols-3 gap-3">{related.map((rp) => (
                      <Card key={rp.id} className="cursor-pointer hover:border-emerald-300 hover:shadow-md transition-all" onClick={() => { setSelectedPost(rp); }}>
                        <div className="h-1.5 bg-gradient-to-r from-emerald-400 to-teal-500" />
                        <CardContent className="p-3">
                          <Badge className={categoryColors[rp.category] || 'bg-slate-100 text-slate-800'} variant="secondary">{rp.category}</Badge>
                          <p className="text-sm font-medium text-slate-900 mt-2 line-clamp-2 leading-snug">{rp.title}</p>
                          <div className="flex items-center gap-2 mt-2 text-xs text-slate-400"><span className="flex items-center gap-1"><Clock className="w-3 h-3" />{rp.readTime || 5} min</span><span className="flex items-center gap-1"><Heart className="w-3 h-3" />{rp.likeCount || 0}</span></div>
                        </CardContent>
                      </Card>))}</div>
                  </div>
                )}

                {/* Comments Section */}
                <div className="mt-6" ref={commentsEndRef}>
                  <Separator className="mb-4" />
                  <h3 className="font-bold text-slate-900 mb-4 flex items-center gap-2"><MessageCircle className="w-5 h-5 text-emerald-600" /> Comments ({comments.length || selectedPost.commentCount || 0})</h3>

                  {/* Add Comment */}
                  <div className="space-y-3 mb-6 p-4 bg-slate-50 rounded-xl border border-slate-100">
                    <div className="flex gap-3">
                      <Input placeholder="Your name" value={commentName} onChange={(e) => setCommentName(e.target.value)} className="flex-1" />
                    </div>
                    <div className="flex gap-3">
                      <Textarea placeholder="Share your thoughts..." rows={3} value={commentText} onChange={(e) => setCommentText(e.target.value)} className="flex-1" />
                      <Button onClick={handleComment} disabled={!commentName.trim() || !commentText.trim() || submittingComment} className="bg-emerald-600 hover:bg-emerald-700 self-end">
                        {submittingComment ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
                      </Button>
                    </div>
                  </div>

                  {/* Comment List */}
                  {comments.length > 0 ? (
                    <div className="space-y-4">{comments.map((comment) => (
                      <div key={comment.id} className="flex gap-3 p-3 bg-white rounded-lg border border-slate-100">
                        <div className="w-8 h-8 bg-gradient-to-br from-slate-300 to-slate-400 rounded-full flex items-center justify-center text-white font-bold text-xs flex-shrink-0">{comment.authorName.charAt(0).toUpperCase()}</div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1"><p className="text-sm font-semibold text-slate-900">{comment.authorName}</p><span className="text-xs text-slate-400">{formatDate(comment.createdAt)}</span></div>
                          <p className="text-sm text-slate-700 leading-relaxed">{comment.content}</p>
                        </div>
                      </div>))}</div>
                  ) : (
                    <p className="text-sm text-slate-400 text-center py-4">Be the first to share your thoughts!</p>
                  )}
                </div>


              </>
            );
          })()}
        </DialogContent>
      </Dialog>

      {/* Scroll to Top */}
      {showScrollTop && (
        <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="fixed bottom-6 right-6 z-40 w-10 h-10 bg-emerald-600 hover:bg-emerald-700 text-white rounded-full shadow-lg flex items-center justify-center transition-all">
          <ChevronUp className="w-5 h-5" />
        </button>
      )}

      {/* Newsletter Banner */}
      {!subscribed && (
        <section className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white py-8">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 text-center">
            <Mail className="w-8 h-8 mx-auto mb-3 text-amber-300" />
            <h3 className="text-xl font-bold mb-2">Get Weekly AI Tool Insights</h3>
            <p className="text-emerald-100 mb-4 text-sm">Join 500+ subscribers. Every new subscriber is notified to <strong>{NEWSLETTER_OWNER}</strong></p>
            <div className="flex flex-col sm:flex-row gap-2 max-w-md mx-auto">
              <Input placeholder="Your email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="bg-white/10 border-white/20 text-white placeholder:text-emerald-200" />
              <Button onClick={handleNewsletter} disabled={!email.includes('@') || subscribing} className="bg-amber-400 hover:bg-amber-500 text-amber-900 font-semibold whitespace-nowrap">
                {subscribing ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <Send className="w-4 h-4 mr-1.5" />}Subscribe
              </Button>
            </div>
          </div>
        </section>
      )}

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 mt-auto">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-lg flex items-center justify-center"><Zap className="w-5 h-5 text-white" /></div>
              <div><p className="text-white font-semibold">AI Toolkit Hub</p><p className="text-xs">by <span className="text-emerald-400 font-medium">Daktari Brian</span></p></div>
            </div>
            <div className="text-center">
              <p className="text-xs text-slate-500">Affiliate Disclosure: Some links earn commissions at no cost to you. I only recommend tools I&apos;ve personally tested.</p>
              <p className="text-xs text-slate-600 mt-1">Powered by AI-driven research &middot; &copy; {new Date().getFullYear()} Daktari Brian</p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
