'use client';

import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
  Shield, Lock, PenTool, Zap, TrendingUp, BarChart3, Eye,
  Trash2, Edit3, Plus, RefreshCw, Settings, Mail, Users,
  FileText, CheckCircle2, AlertCircle, Loader2, ExternalLink,
  Clock, Heart, MessageCircle, Share2, Globe, Key,
} from 'lucide-react';

const ADMIN_PASSWORD = 'Daktari2026!'; // Change this to your own password

interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string;
  category: string;
  tags: string;
  featured: boolean;
  trending: boolean;
  published: boolean;
  autoGenerated: boolean;
  viewCount: number;
  likeCount: number;
  shareCount: number;
  commentCount: number;
  authorName: string;
  readTime: number;
  publishedAt: string | null;
  createdAt: string;
}

interface Subscriber {
  id: string;
  email: string;
  name: string | null;
  active: boolean;
  source: string;
  createdAt: string;
}

interface Comment {
  id: string;
  blogPostId: string;
  authorName: string;
  content: string;
  flagged: boolean;
  createdAt: string;
  postTitle?: string;
}

export default function AdminPanel() {
  const [authenticated, setAuthenticated] = useState(false);
  const [password, setPassword] = useState('');
  const [passwordError, setPasswordError] = useState('');
  const [activeTab, setActiveTab] = useState<'posts' | 'create' | 'subscribers' | 'comments' | 'autopost' | 'settings'>('posts');

  // Posts state
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [loadingPosts, setLoadingPosts] = useState(false);

  // Create post state
  const [newTitle, setNewTitle] = useState('');
  const [newContent, setNewContent] = useState('');
  const [newExcerpt, setNewExcerpt] = useState('');
  const [newCategory, setNewCategory] = useState('AI Tools');
  const [newTags, setNewTags] = useState('');
  const [newPublished, setNewPublished] = useState(true);
  const [newFeatured, setNewFeatured] = useState(false);
  const [creating, setCreating] = useState(false);

  // Autopost state
  const [autoposting, setAutoposting] = useState(false);
  const [autopostResult, setAutopostResult] = useState<string>('');

  // Subscribers
  const [subscribers, setSubscribers] = useState<Subscriber[]>([]);
  const [loadingSubs, setLoadingSubs] = useState(false);

  // Comments
  const [comments, setComments] = useState<Comment[]>([]);
  const [loadingComments, setLoadingComments] = useState(false);

  // Trending research
  const [researching, setResearching] = useState(false);
  const [researchResult, setResearchResult] = useState('');

  // Stats
  const [stats, setStats] = useState({ totalPosts: 0, publishedPosts: 0, autoGenerated: 0, trendingTopics: 0 });

  function handleLogin() {
    if (password === ADMIN_PASSWORD) {
      setAuthenticated(true);
      setPasswordError('');
    } else {
      setPasswordError('Wrong password. Try again.');
    }
  }

  async function loadPosts() {
    setLoadingPosts(true);
    try {
      const res = await fetch('/api/blog?limit=50');
      const data = await res.json();
      setPosts(data.posts || []);
    } catch (e) {
      console.error(e);
    }
    setLoadingPosts(false);
  }

  async function loadSubscribers() {
    setLoadingSubs(true);
    try {
      const res = await fetch('/api/newsletter');
      const data = await res.json();
      // For now just show count - full list would need a new endpoint
      setSubscribers([]);
    } catch (e) {
      console.error(e);
    }
    setLoadingSubs(false);
  }

  async function loadComments() {
    setLoadingComments(true);
    try {
      const res = await fetch('/api/blog?limit=50');
      const data = await res.json();
      // Load comments for each post would need a batch endpoint
      setComments([]);
    } catch (e) {
      console.error(e);
    }
    setLoadingComments(false);
  }

  async function loadStats() {
    try {
      const res = await fetch('/api/autopost');
      const data = await res.json();
      setStats(data.stats || { totalPosts: 0, publishedPosts: 0, autoGenerated: 0, trendingTopics: 0 });
    } catch (e) {
      console.error(e);
    }
  }

  async function createPost() {
    if (!newTitle || !newContent) return;
    setCreating(true);
    try {
      const slug = newTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60);
      const res = await fetch('/api/blog', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: newTitle,
          slug,
          content: newContent,
          excerpt: newExcerpt || newTitle,
          category: newCategory,
          tags: newTags || newCategory,
          published: newPublished,
          featured: newFeatured,
          trending: false,
          authorName: 'Daktari Brian',
          readTime: Math.ceil(newContent.split(/\s+/).length / 200),
        }),
      });
      if (res.ok) {
        setNewTitle(''); setNewContent(''); setNewExcerpt(''); setNewTags('');
        setNewPublished(true); setNewFeatured(false);
        loadPosts(); loadStats();
      }
    } catch (e) {
      console.error(e);
    }
    setCreating(false);
  }

  async function deletePost(id: string) {
    if (!confirm('Delete this post? This cannot be undone.')) return;
    try {
      await fetch(`/api/blog/${id}`, { method: 'DELETE' });
      loadPosts(); loadStats();
    } catch (e) {
      console.error(e);
    }
  }

  async function togglePublish(id: string, published: boolean) {
    try {
      await fetch(`/api/blog/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ published: !published }),
      });
      loadPosts(); loadStats();
    } catch (e) {
      console.error(e);
    }
  }

  async function researchTrending() {
    setResearching(true);
    setResearchResult('');
    try {
      const res = await fetch('/api/trending', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ category: 'AI Tools' }),
      });
      const data = await res.json();
      setResearchResult(`Found ${data.newTopicsFound || 0} new trending topics! Total: ${data.topics?.length || 0}`);
      loadStats();
    } catch (e) {
      setResearchResult('Research failed. Make sure OPENROUTER_API_KEY is set.');
    }
    setResearching(false);
  }

  async function autoGeneratePosts() {
    setAutoposting(true);
    setAutopostResult('');
    try {
      const res = await fetch('/api/autopost', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ count: 1, autoPublish: false }),
      });
      const data = await res.json();
      if (data.created) {
        setAutopostResult(`Generated ${data.created} post(s)! They are saved as drafts. Publish them when ready.`);
      } else if (data.error) {
        setAutopostResult(`Error: ${data.error}`);
      }
      loadPosts(); loadStats();
    } catch (e) {
      setAutopostResult('Auto-post failed. Make sure OPENROUTER_API_KEY is set.');
    }
    setAutoposting(false);
  }

  useEffect(() => {
    if (authenticated) {
      loadPosts();
      loadStats();
    }
  }, [authenticated]);

  // ─── LOGIN SCREEN ─────────────────────────
  if (!authenticated) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-900 flex items-center justify-center p-4">
        <Card className="w-full max-w-md border-emerald-800/50 bg-slate-900/80 backdrop-blur">
          <CardHeader className="text-center">
            <div className="w-16 h-16 bg-emerald-600 rounded-2xl flex items-center justify-center mx-auto mb-4">
              <Shield className="w-8 h-8 text-white" />
            </div>
            <CardTitle className="text-2xl text-white">Admin Panel</CardTitle>
            <CardDescription className="text-slate-400">AI Toolkit Hub — Daktari Brian</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Input
                type="password"
                placeholder="Enter admin password"
                value={password}
                onChange={(e) => { setPassword(e.target.value); setPasswordError(''); }}
                onKeyDown={(e) => e.key === 'Enter' && handleLogin()}
                className="bg-slate-800 border-slate-700 text-white text-center text-lg"
              />
              {passwordError && <p className="text-red-400 text-sm mt-2 text-center">{passwordError}</p>}
            </div>
            <Button onClick={handleLogin} className="w-full bg-emerald-600 hover:bg-emerald-700 text-white">
              <Lock className="w-4 h-4 mr-2" /> Unlock Dashboard
            </Button>
            <p className="text-slate-500 text-xs text-center">This area is for site administrators only.</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  // ─── ADMIN DASHBOARD ──────────────────────
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-900">
      {/* Header */}
      <header className="border-b border-slate-700/50 bg-slate-900/80 backdrop-blur sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-emerald-600 rounded-xl flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <div>
              <h1 className="text-white font-bold text-lg">AI Toolkit Hub</h1>
              <p className="text-emerald-400 text-xs">Admin Dashboard — Daktari Brian</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <a href="/" target="_blank" className="text-slate-400 hover:text-white text-sm flex items-center gap-1">
              <Globe className="w-4 h-4" /> View Site
            </a>
            <Button variant="outline" size="sm" onClick={() => setAuthenticated(false)} className="border-slate-600 text-slate-300">
              <Lock className="w-4 h-4 mr-1" /> Lock
            </Button>
          </div>
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-4 py-6">
        {/* Stats Bar */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {[
            { label: 'Total Posts', value: stats.totalPosts, icon: FileText, color: 'text-blue-400' },
            { label: 'Published', value: stats.publishedPosts, icon: Eye, color: 'text-emerald-400' },
            { label: 'AI Generated', value: stats.autoGenerated, icon: Zap, color: 'text-purple-400' },
            { label: 'Trending Topics', value: stats.trendingTopics, icon: TrendingUp, color: 'text-amber-400' },
          ].map((stat) => (
            <Card key={stat.label} className="bg-slate-800/50 border-slate-700/50">
              <CardContent className="p-4 flex items-center gap-3">
                <stat.icon className={`w-8 h-8 ${stat.color}`} />
                <div>
                  <p className="text-2xl font-bold text-white">{stat.value}</p>
                  <p className="text-slate-400 text-xs">{stat.label}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Tab Navigation */}
        <div className="flex gap-2 mb-6 overflow-x-auto pb-2">
          {[
            { id: 'posts', label: 'All Posts', icon: FileText },
            { id: 'create', label: 'Write Post', icon: PenTool },
            { id: 'autopost', label: 'AI Auto-Post', icon: Zap },
            { id: 'subscribers', label: 'Subscribers', icon: Users },
            { id: 'comments', label: 'Comments', icon: MessageCircle },
            { id: 'settings', label: 'Settings', icon: Settings },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => {
                setActiveTab(tab.id as typeof activeTab);
                if (tab.id === 'posts') loadPosts();
                if (tab.id === 'subscribers') loadSubscribers();
              }}
              className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-colors ${
                activeTab === tab.id
                  ? 'bg-emerald-600 text-white'
                  : 'bg-slate-800/50 text-slate-400 hover:text-white hover:bg-slate-700/50'
              }`}
            >
              <tab.icon className="w-4 h-4" />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        {activeTab === 'posts' && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-bold text-white">All Posts</h2>
              <Button onClick={loadPosts} variant="outline" size="sm" className="border-slate-600 text-slate-300">
                <RefreshCw className="w-4 h-4 mr-1" /> Refresh
              </Button>
            </div>
            {loadingPosts ? (
              <div className="text-center py-12 text-slate-400"><Loader2 className="w-8 h-8 animate-spin mx-auto mb-2" />Loading posts...</div>
            ) : posts.length === 0 ? (
              <Card className="bg-slate-800/50 border-slate-700/50">
                <CardContent className="p-8 text-center text-slate-400">
                  <FileText className="w-12 h-12 mx-auto mb-3 text-slate-600" />
                  <p>No posts yet. Create your first post or use AI auto-post!</p>
                </CardContent>
              </Card>
            ) : (
              posts.map((post) => (
                <Card key={post.id} className="bg-slate-800/50 border-slate-700/50">
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap mb-1">
                          <h3 className="text-white font-semibold truncate">{post.title}</h3>
                          {post.published ? (
                            <Badge className="bg-emerald-600/20 text-emerald-400 border-emerald-600/30 text-xs">Published</Badge>
                          ) : (
                            <Badge className="bg-amber-600/20 text-amber-400 border-amber-600/30 text-xs">Draft</Badge>
                          )}
                          {post.featured && <Badge className="bg-blue-600/20 text-blue-400 border-blue-600/30 text-xs">Featured</Badge>}
                          {post.trending && <Badge className="bg-purple-600/20 text-purple-400 border-purple-600/30 text-xs">Trending</Badge>}
                          {post.autoGenerated && <Badge className="bg-pink-600/20 text-pink-400 border-pink-600/30 text-xs">AI Generated</Badge>}
                        </div>
                        <div className="flex items-center gap-4 text-slate-500 text-xs">
                          <span className="flex items-center gap-1"><Eye className="w-3 h-3" />{post.viewCount}</span>
                          <span className="flex items-center gap-1"><Heart className="w-3 h-3" />{post.likeCount}</span>
                          <span className="flex items-center gap-1"><MessageCircle className="w-3 h-3" />{post.commentCount}</span>
                          <span className="flex items-center gap-1"><Share2 className="w-3 h-3" />{post.shareCount}</span>
                          <span className="flex items-center gap-1"><Clock className="w-3 h-3" />{post.readTime} min</span>
                          <span>by {post.authorName}</span>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Button onClick={() => togglePublish(post.id, post.published)} variant="outline" size="sm"
                          className={post.published ? 'border-amber-600/50 text-amber-400' : 'border-emerald-600/50 text-emerald-400'}>
                          {post.published ? 'Unpublish' : 'Publish'}
                        </Button>
                        <Button onClick={() => deletePost(post.id)} variant="outline" size="sm" className="border-red-600/50 text-red-400">
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))
            )}
          </div>
        )}

        {activeTab === 'create' && (
          <Card className="bg-slate-800/50 border-slate-700/50">
            <CardHeader>
              <CardTitle className="text-white">Write New Post</CardTitle>
              <CardDescription className="text-slate-400">Create a blog post as Daktari Brian</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <Input placeholder="Post title..." value={newTitle} onChange={(e) => setNewTitle(e.target.value)}
                className="bg-slate-900 border-slate-700 text-white text-lg" />
              <Input placeholder="Short excerpt (appears in card previews)" value={newExcerpt} onChange={(e) => setNewExcerpt(e.target.value)}
                className="bg-slate-900 border-slate-700 text-white" />
              <div className="grid grid-cols-3 gap-3">
                <Input placeholder="Category (e.g., AI Tools)" value={newCategory} onChange={(e) => setNewCategory(e.target.value)}
                  className="bg-slate-900 border-slate-700 text-white" />
                <Input placeholder="Tags (comma separated)" value={newTags} onChange={(e) => setNewTags(e.target.value)}
                  className="bg-slate-900 border-slate-700 text-white" />
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-2 text-slate-300 text-sm cursor-pointer">
                    <input type="checkbox" checked={newPublished} onChange={(e) => setNewPublished(e.target.checked)} className="accent-emerald-600" />
                    Publish
                  </label>
                  <label className="flex items-center gap-2 text-slate-300 text-sm cursor-pointer">
                    <input type="checkbox" checked={newFeatured} onChange={(e) => setNewFeatured(e.target.checked)} className="accent-blue-600" />
                    Featured
                  </label>
                </div>
              </div>
              <Textarea placeholder="Write your post content here (HTML supported)..." value={newContent}
                onChange={(e) => setNewContent(e.target.value)} rows={15}
                className="bg-slate-900 border-slate-700 text-white font-mono text-sm" />
              <Button onClick={createPost} disabled={creating || !newTitle || !newContent}
                className="bg-emerald-600 hover:bg-emerald-700 text-white">
                {creating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Plus className="w-4 h-4 mr-2" />}
                Publish Post
              </Button>
            </CardContent>
          </Card>
        )}

        {activeTab === 'autopost' && (
          <div className="space-y-4">
            {/* Research Trending Topics */}
            <Card className="bg-slate-800/50 border-slate-700/50">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-amber-400" /> Research Trending Topics
                </CardTitle>
                <CardDescription className="text-slate-400">
                  Find what people are searching for right now. Uses SerpAPI (if configured) or AI research.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Button onClick={researchTrending} disabled={researching} className="bg-amber-600 hover:bg-amber-700 text-white">
                  {researching ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Search className="w-4 h-4 mr-2" />}
                  Research Now
                </Button>
                {researchResult && (
                  <div className="mt-3 p-3 bg-slate-900/50 rounded-lg text-sm text-emerald-400 flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4" /> {researchResult}
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Auto-Generate Posts */}
            <Card className="bg-slate-800/50 border-slate-700/50">
              <CardHeader>
                <CardTitle className="text-white flex items-center gap-2">
                  <Zap className="w-5 h-5 text-purple-400" /> AI Auto-Post Generator
                </CardTitle>
                <CardDescription className="text-slate-400">
                  AI picks the best trending topic and writes a full SEO-optimized blog post as a draft.
                  Requires OPENROUTER_API_KEY to be set.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="p-3 bg-amber-900/20 border border-amber-600/30 rounded-lg text-amber-300 text-sm flex items-start gap-2">
                  <AlertCircle className="w-4 h-4 mt-0.5 shrink-0" />
                  <span>Posts are created as <strong>drafts</strong> — you review and publish them from the All Posts tab. Always edit AI content before publishing for best SEO results.</span>
                </div>
                <Button onClick={autoGeneratePosts} disabled={autoposting} className="bg-purple-600 hover:bg-purple-700 text-white">
                  {autoposting ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Zap className="w-4 h-4 mr-2" />}
                  Generate 1 AI Post (Draft)
                </Button>
                {autopostResult && (
                  <div className={`mt-2 p-3 rounded-lg text-sm flex items-center gap-2 ${autopostResult.includes('Error') || autopostResult.includes('Failed') ? 'bg-red-900/20 text-red-400' : 'bg-emerald-900/20 text-emerald-400'}`}>
                    {autopostResult.includes('Error') ? <AlertCircle className="w-4 h-4" /> : <CheckCircle2 className="w-4 h-4" />}
                    {autopostResult}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        )}

        {activeTab === 'subscribers' && (
          <Card className="bg-slate-800/50 border-slate-700/50">
            <CardHeader>
              <CardTitle className="text-white">Newsletter Subscribers</CardTitle>
              <CardDescription className="text-slate-400">People who signed up via the newsletter form</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-slate-400 text-sm">Subscriber count: Check via /api/newsletter (GET). Full list management coming soon.</p>
              <p className="text-slate-500 text-xs mt-2">Notifications are sent to: koechbrian245@gmail.com</p>
            </CardContent>
          </Card>
        )}

        {activeTab === 'comments' && (
          <Card className="bg-slate-800/50 border-slate-700/50">
            <CardHeader>
              <CardTitle className="text-white">Manage Comments</CardTitle>
              <CardDescription className="text-slate-400">Review, approve, or flag visitor comments</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-slate-400 text-sm">Comments are automatically filtered for spam. Flagged comments will be hidden from visitors.</p>
              <p className="text-slate-500 text-xs mt-2">Full comment management dashboard coming soon.</p>
            </CardContent>
          </Card>
        )}

        {activeTab === 'settings' && (
          <div className="space-y-4">
            <Card className="bg-slate-800/50 border-slate-700/50">
              <CardHeader>
                <CardTitle className="text-white">Site Settings</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-slate-300 text-sm font-medium">Admin Password</label>
                  <p className="text-slate-500 text-xs mb-2">Currently: hardcoded in /src/app/admin/page.tsx. Change ADMIN_PASSWORD constant.</p>
                  <div className="p-3 bg-slate-900/50 rounded-lg text-sm text-amber-300 flex items-start gap-2">
                    <Key className="w-4 h-4 mt-0.5 shrink-0" />
                    <span>To change the admin password, edit the <code className="bg-slate-800 px-1 rounded">ADMIN_PASSWORD</code> variable in <code className="bg-slate-800 px-1 rounded">src/app/admin/page.tsx</code></span>
                  </div>
                </div>
                <Separator className="bg-slate-700" />
                <div>
                  <label className="text-slate-300 text-sm font-medium">Required Environment Variables</label>
                  <div className="mt-2 space-y-2">
                    {[
                      { key: 'DATABASE_URL', desc: 'PostgreSQL connection string (Neon)', required: true },
                      { key: 'OPENROUTER_API_KEY', desc: 'For AI auto-post generation', required: true },
                      { key: 'SERPAPI_KEY', desc: 'For real web search (optional)', required: false },
                      { key: 'RESEND_API_KEY', desc: 'For email notifications (optional)', required: false },
                      { key: 'OWNER_EMAIL', desc: 'Your email for notifications', required: false },
                    ].map((env) => (
                      <div key={env.key} className="flex items-center gap-2 text-sm">
                        <Badge className={env.required ? 'bg-red-600/20 text-red-400 border-red-600/30' : 'bg-slate-600/20 text-slate-400 border-slate-600/30'}>
                          {env.required ? 'Required' : 'Optional'}
                        </Badge>
                        <code className="text-emerald-400 bg-slate-900 px-2 py-0.5 rounded">{env.key}</code>
                        <span className="text-slate-500">— {env.desc}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <Separator className="bg-slate-700" />
                <div>
                  <label className="text-slate-300 text-sm font-medium">Affiliate Links</label>
                  <p className="text-slate-500 text-xs mb-2">Current links are placeholders pointing to product homepages. You need to:</p>
                  <ol className="text-slate-400 text-sm space-y-1 list-decimal list-inside">
                    <li>Sign up for each affiliate program (Jasper, Surfer, GetResponse, etc.)</li>
                    <li>Get your unique referral URL</li>
                    <li>Replace the URLs in the autopost route and seed data</li>
                  </ol>
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
