import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { searchTrendingTopics, generateBlogPost } from '@/lib/ai-service';

// POST /api/autopost - Auto-generate and publish blog posts
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { count = 1, autoPublish = false } = body as { count?: number; autoPublish?: boolean };

    // Get unused trending topics with highest scores
    const topics = await db.trendingTopic.findMany({
      where: { usedForPost: false },
      orderBy: { trendScore: 'desc' },
      take: count * 3, // Get extra in case some fail
    });

    if (topics.length === 0) {
      return NextResponse.json({ error: 'No trending topics available. Research topics first.' }, { status: 400 });
    }

    const created = [];

    for (let i = 0; i < Math.min(count, topics.length); i++) {
      const topic = topics[i];

      try {
        // Search for more context
        const searchResults = await searchTrendingTopics(topic.keyword, 5);
        const keywords = searchResults.slice(0, 3).map((r: { name?: string }) => r.name || '').filter(Boolean);

        // Generate blog post with AI
        const blogData = await generateBlogPost(
          topic.keyword,
          keywords.length > 0 ? keywords : [topic.keyword],
          topic.category
        );

        if (!blogData) continue;

        // Create the blog post
        const slug = blogData.slug || topic.keyword.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60);

        // Check for duplicate slug
        const existing = await db.blogPost.findFirst({ where: { slug } });
        if (existing) continue;

        const post = await db.blogPost.create({
          data: {
            title: blogData.title || topic.keyword,
            slug,
            excerpt: blogData.excerpt || '',
            content: blogData.content || '',
            category: topic.category,
            tags: JSON.stringify(blogData.tags || []),
            seoTitle: blogData.seoTitle || blogData.title,
            seoDesc: blogData.seoDesc || blogData.excerpt,
            trending: true,
            published: autoPublish,
            autoGenerated: true,
            sourceUrl: topic.rawData ? JSON.parse(topic.rawData).url : undefined,
            publishedAt: autoPublish ? new Date() : null,
          },
        });

        // Create affiliate links for mentioned tools
        if (blogData.affiliateTools && Array.isArray(blogData.affiliateTools)) {
          const affiliatePrograms: Record<string, { url: string; rate: string }> = {
            'Jasper': { url: 'https://jasper.ai/?fpr=ai-toolkit', rate: '25-30% recurring' },
            'Surfer SEO': { url: 'https://surferseo.com/?fpr=ai-toolkit', rate: '10-20% recurring' },
            'Writesonic': { url: 'https://writesonic.com/?fpr=ai-toolkit', rate: '30% recurring' },
            'GetResponse': { url: 'https://www.getresponse.com/?a=ai-toolkit', rate: '33% recurring' },
            'HubSpot': { url: 'https://hubspot.com/?fpr=ai-toolkit', rate: 'Up to $1,000/referral' },
            'Canva': { url: 'https://canva.com/?fpr=ai-toolkit', rate: 'Up to $36/subscription' },
            'Notion': { url: 'https://notion.so/?fpr=ai-toolkit', rate: 'Up to $10/referral' },
            'CustomGPT': { url: 'https://customgpt.ai/?fpr=ai-toolkit', rate: '15-20% recurring' },
            'Copy.ai': { url: 'https://copy.ai/?fpr=ai-toolkit', rate: '25% recurring' },
            'Semrush': { url: 'https://semrush.com/?fpr=ai-toolkit', rate: '$200/subscription' },
            'Ahrefs': { url: 'https://ahrefs.com/?fpr=ai-toolkit', rate: '20% recurring' },
            'Midjourney': { url: 'https://midjourney.com/?fpr=ai-toolkit', rate: '15% recurring' },
          };

          for (let j = 0; j < blogData.affiliateTools.length; j++) {
            const toolName = blogData.affiliateTools[j];
            const program = affiliatePrograms[toolName];
            if (program) {
              await db.affiliateLink.create({
                data: {
                  blogPostId: post.id,
                  toolName,
                  affiliateUrl: program.url,
                  commissionRate: program.rate,
                  commissionType: 'recurring',
                  description: `${toolName} - AI-powered tool`,
                  displayOrder: j,
                },
              });
            }
          }
        }

        // Mark topic as used
        await db.trendingTopic.update({
          where: { id: topic.id },
          data: { usedForPost: true },
        });

        created.push(post);
      } catch (e) {
        console.error('Failed to create post from topic:', topic.keyword, e);
      }
    }

    // Update auto-post config
    await db.autoPostConfig.upsert({
      where: { id: 'default' },
      update: { lastRunAt: new Date() },
      create: { id: 'default', lastRunAt: new Date() },
    });

    return NextResponse.json({ created: created.length, posts: created });
  } catch (error) {
    console.error('Autopost error:', error);
    return NextResponse.json({ error: 'Failed to auto-post' }, { status: 500 });
  }
}

// GET /api/autopost - Get autopost config
export async function GET() {
  try {
    const config = await db.autoPostConfig.findUnique({ where: { id: 'default' } });
    const stats = {
      totalPosts: await db.blogPost.count(),
      publishedPosts: await db.blogPost.count({ where: { published: true } }),
      autoGeneratedPosts: await db.blogPost.count({ where: { autoGenerated: true } }),
      trendingTopics: await db.trendingTopic.count({ where: { usedForPost: false } }),
    };
    return NextResponse.json({ config, stats });
  } catch (error) {
    console.error('Autopost GET error:', error);
    return NextResponse.json({ error: 'Failed to get config' }, { status: 500 });
  }
}
